simple.i: parsing
simple.i: parsed
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void print_hello(void) ;
#line 37 "/usr/include/i386/_types.h"
typedef signed char __int8_t;
#line 41 "/usr/include/i386/_types.h"
typedef unsigned char __uint8_t;
#line 42 "/usr/include/i386/_types.h"
typedef short __int16_t;
#line 43 "/usr/include/i386/_types.h"
typedef unsigned short __uint16_t;
#line 44 "/usr/include/i386/_types.h"
typedef int __int32_t;
#line 45 "/usr/include/i386/_types.h"
typedef unsigned int __uint32_t;
#line 46 "/usr/include/i386/_types.h"
typedef long long __int64_t;
#line 47 "/usr/include/i386/_types.h"
typedef unsigned long long __uint64_t;
#line 49 "/usr/include/i386/_types.h"
typedef long __darwin_intptr_t;
#line 50 "/usr/include/i386/_types.h"
typedef unsigned int __darwin_natural_t;
#line 70 "/usr/include/i386/_types.h"
typedef int __darwin_ct_rune_t;
#line 76 "/usr/include/i386/_types.h"
union __anonunion___mbstate_t_1 {
   char __mbstate8[128] ;
   long long _mbstateL ;
};
#line 76 "/usr/include/i386/_types.h"
typedef union __anonunion___mbstate_t_1 __mbstate_t;
#line 81 "/usr/include/i386/_types.h"
typedef __mbstate_t __darwin_mbstate_t;
#line 84 "/usr/include/i386/_types.h"
typedef long __darwin_ptrdiff_t;
#line 92 "/usr/include/i386/_types.h"
typedef unsigned long __darwin_size_t;
#line 98 "/usr/include/i386/_types.h"
typedef __builtin_va_list __darwin_va_list;
#line 104 "/usr/include/i386/_types.h"
typedef int __darwin_wchar_t;
#line 109 "/usr/include/i386/_types.h"
typedef __darwin_wchar_t __darwin_rune_t;
#line 112 "/usr/include/i386/_types.h"
typedef int __darwin_wint_t;
#line 117 "/usr/include/i386/_types.h"
typedef unsigned long __darwin_clock_t;
#line 118 "/usr/include/i386/_types.h"
typedef __uint32_t __darwin_socklen_t;
#line 119 "/usr/include/i386/_types.h"
typedef long __darwin_ssize_t;
#line 120 "/usr/include/i386/_types.h"
typedef long __darwin_time_t;
#line 55 "/usr/include/sys/_types.h"
typedef __int64_t __darwin_blkcnt_t;
#line 56 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_blksize_t;
#line 57 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_dev_t;
#line 58 "/usr/include/sys/_types.h"
typedef unsigned int __darwin_fsblkcnt_t;
#line 59 "/usr/include/sys/_types.h"
typedef unsigned int __darwin_fsfilcnt_t;
#line 60 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_gid_t;
#line 61 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_id_t;
#line 62 "/usr/include/sys/_types.h"
typedef __uint64_t __darwin_ino64_t;
#line 64 "/usr/include/sys/_types.h"
typedef __darwin_ino64_t __darwin_ino_t;
#line 68 "/usr/include/sys/_types.h"
typedef __darwin_natural_t __darwin_mach_port_name_t;
#line 69 "/usr/include/sys/_types.h"
typedef __darwin_mach_port_name_t __darwin_mach_port_t;
#line 70 "/usr/include/sys/_types.h"
typedef __uint16_t __darwin_mode_t;
#line 71 "/usr/include/sys/_types.h"
typedef __int64_t __darwin_off_t;
#line 72 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_pid_t;
#line 73 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_sigset_t;
#line 74 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_suseconds_t;
#line 75 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_uid_t;
#line 76 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_useconds_t;
#line 77 "/usr/include/sys/_types.h"
typedef unsigned char __darwin_uuid_t[16];
#line 78 "/usr/include/sys/_types.h"
typedef char __darwin_uuid_string_t[37];
#line 57 "/usr/include/sys/_pthread/_pthread_types.h"
struct __darwin_pthread_handler_rec {
   void (*__routine)(void * ) ;
   void *__arg ;
   struct __darwin_pthread_handler_rec *__next ;
};
#line 63 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_attr_t {
   long __sig ;
   char __opaque[56] ;
};
#line 68 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_cond_t {
   long __sig ;
   char __opaque[40] ;
};
#line 73 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_condattr_t {
   long __sig ;
   char __opaque[8] ;
};
#line 78 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_mutex_t {
   long __sig ;
   char __opaque[56] ;
};
#line 83 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_mutexattr_t {
   long __sig ;
   char __opaque[8] ;
};
#line 88 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_once_t {
   long __sig ;
   char __opaque[8] ;
};
#line 93 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_rwlock_t {
   long __sig ;
   char __opaque[192] ;
};
#line 98 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_rwlockattr_t {
   long __sig ;
   char __opaque[16] ;
};
#line 103 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_t {
   long __sig ;
   struct __darwin_pthread_handler_rec *__cleanup_stack ;
   char __opaque[8176] ;
};
#line 109 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_attr_t __darwin_pthread_attr_t;
#line 110 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_cond_t __darwin_pthread_cond_t;
#line 111 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_condattr_t __darwin_pthread_condattr_t;
#line 112 "/usr/include/sys/_pthread/_pthread_types.h"
typedef unsigned long __darwin_pthread_key_t;
#line 113 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_mutex_t __darwin_pthread_mutex_t;
#line 114 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_mutexattr_t __darwin_pthread_mutexattr_t;
#line 115 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_once_t __darwin_pthread_once_t;
#line 116 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_rwlock_t __darwin_pthread_rwlock_t;
#line 117 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_rwlockattr_t __darwin_pthread_rwlockattr_t;
#line 118 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_t *__darwin_pthread_t;
#line 39 "/usr/include/_types.h"
typedef int __darwin_nl_item;
#line 40 "/usr/include/_types.h"
typedef int __darwin_wctrans_t;
#line 42 "/usr/include/_types.h"
typedef __uint32_t __darwin_wctype_t;
#line 31 "/usr/include/sys/_types/_va_list.h"
typedef __darwin_va_list va_list;
#line 30 "/usr/include/sys/_types/_size_t.h"
typedef __darwin_size_t size_t;
#line 77 "/usr/include/stdio.h"
typedef __darwin_off_t fpos_t;
#line 88 "/usr/include/stdio.h"
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
#line 94
struct __sFILEX;
#line 94
struct __sFILEX;
#line 122 "/usr/include/stdio.h"
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (*_close)(void * ) ;
   int (*_read)(void * , char * , int  ) ;
   fpos_t (*_seek)(void * , fpos_t  , int  ) ;
   int (*_write)(void * , char const   * , int  ) ;
   struct __sbuf _ub ;
   struct __sFILEX *_extra ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
#line 122 "/usr/include/stdio.h"
typedef struct __sFILE FILE;
#line 30 "/usr/include/sys/_types/_off_t.h"
typedef __darwin_off_t off_t;
#line 30 "/usr/include/sys/_types/_ssize_t.h"
typedef __darwin_ssize_t ssize_t;
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
#line 39 "/usr/include/sys/stdio.h"
extern int renameat(int  , char const   * , int  , char const   * ) ;
#line 156 "/usr/include/stdio.h"
extern FILE *__stdinp ;
#line 157
extern FILE *__stdoutp ;
#line 158
extern FILE *__stderrp ;
#line 231
extern void clearerr(FILE * ) ;
#line 232
extern int fclose(FILE * ) ;
#line 233
extern int feof(FILE * ) ;
#line 234
extern int ferror(FILE * ) ;
#line 235
extern int fflush(FILE * ) ;
#line 236
extern int fgetc(FILE * ) ;
#line 237
extern int fgetpos(FILE * __restrict   , fpos_t * ) ;
#line 238
extern char *fgets(char * __restrict   , int  , FILE * ) ;
#line 242
extern FILE *fopen(char const   * __restrict   , char const   * __restrict   )  __asm__("_fopen")  ;
#line 244
extern int ( /* format attribute */  fprintf)(FILE * __restrict   , char const   * __restrict   
                                              , ...) ;
#line 245
extern int fputc(int  , FILE * ) ;
#line 246
extern int fputs(char const   * __restrict   , FILE * __restrict   )  __asm__("_fputs")  ;
#line 247
extern size_t fread(void * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 248
extern FILE *freopen(char const   * __restrict   , char const   * __restrict   , FILE * __restrict   )  __asm__("_freopen")  ;
#line 250
extern int ( /* format attribute */  fscanf)(FILE * __restrict   , char const   * __restrict   
                                             , ...) ;
#line 251
extern int fseek(FILE * , long  , int  ) ;
#line 252
extern int fsetpos(FILE * , fpos_t const   * ) ;
#line 253
extern long ftell(FILE * ) ;
#line 254
extern size_t fwrite(void const   * __restrict   , size_t  , size_t  , FILE * __restrict   )  __asm__("_fwrite")  ;
#line 255
extern int getc(FILE * ) ;
#line 256
extern int getchar(void) ;
#line 257
extern char *gets(char * ) ;
#line 258
extern void perror(char const   * ) ;
#line 259
extern int ( /* format attribute */  printf)(char const   * __restrict    , ...) ;
#line 260
extern int putc(int  , FILE * ) ;
#line 261
extern int putchar(int  ) ;
#line 262
extern int puts(char const   * ) ;
#line 263
extern int remove(char const   * ) ;
#line 264
extern int rename(char const   * , char const   * ) ;
#line 265
extern void rewind(FILE * ) ;
#line 266
extern int ( /* format attribute */  scanf)(char const   * __restrict    , ...) ;
#line 267
extern void setbuf(FILE * __restrict   , char * __restrict   ) ;
#line 268
extern int setvbuf(FILE * __restrict   , char * __restrict   , int  , size_t  ) ;
#line 269
extern int ( /* format attribute */  sprintf)(char * __restrict   , char const   * __restrict   
                                              , ...) ;
#line 270
extern int ( /* format attribute */  sscanf)(char const   * __restrict   , char const   * __restrict   
                                             , ...) ;
#line 271
extern FILE *tmpfile(void) ;
#line 274
extern char __attribute__((__deprecated__("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead.")))  *tmpnam(char * ) ;
#line 277
extern int ungetc(int  , FILE * ) ;
#line 278
extern int ( /* format attribute */  vfprintf)(FILE * __restrict   , char const   * __restrict   ,
                                               va_list  ) ;
#line 279
extern int ( /* format attribute */  vprintf)(char const   * __restrict   , va_list  ) ;
#line 280
extern int ( /* format attribute */  vsprintf)(char * __restrict   , char const   * __restrict   ,
                                               va_list  ) ;
#line 296
extern char *ctermid(char * ) ;
#line 302
extern FILE *fdopen(int  , char const   * )  __asm__("_fdopen")  ;
#line 304
extern int fileno(FILE * ) ;
#line 315
extern int pclose(FILE * ) ;
#line 319
extern FILE *popen(char const   * , char const   * )  __asm__("_popen")  ;
#line 337
extern int __srget(FILE * ) ;
#line 338
extern int ( /* format attribute */  __svfscanf)(FILE * , char const   * , va_list  ) ;
#line 339
extern int __swbuf(int  , FILE * ) ;
#line 348 "/usr/include/stdio.h"
__inline extern int __attribute__((__gnu_inline__))  ( __attribute__((__always_inline__)) __sputc)(int _c ,
                                                                                                   FILE *_p ) 
{ 
  unsigned char *tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;

  {
#line 349
  (_p->_w) --;
#line 349
  if (_p->_w >= 0) {
#line 350
    tmp = _p->_p;
#line 350
    (_p->_p) ++;
#line 350
    tmp___0 = (unsigned char )_c;
#line 350
    *tmp = tmp___0;
#line 350
    return ((int __attribute__((__gnu_inline__))  )tmp___0);
  } else
#line 349
  if (_p->_w >= _p->_lbfsize) {
#line 349
    if ((int )((char )_c) != 10) {
#line 350
      tmp = _p->_p;
#line 350
      (_p->_p) ++;
#line 350
      tmp___0 = (unsigned char )_c;
#line 350
      *tmp = tmp___0;
#line 350
      return ((int __attribute__((__gnu_inline__))  )tmp___0);
    } else {
#line 352
      tmp___1 = __swbuf(_c, _p);
#line 352
      return ((int __attribute__((__gnu_inline__))  )tmp___1);
    }
  } else {
#line 352
    tmp___1 = __swbuf(_c, _p);
#line 352
    return ((int __attribute__((__gnu_inline__))  )tmp___1);
  }
}
}
#line 374
extern void flockfile(FILE * ) ;
#line 375
extern int ftrylockfile(FILE * ) ;
#line 376
extern void funlockfile(FILE * ) ;
#line 377
extern int getc_unlocked(FILE * ) ;
#line 378
extern int getchar_unlocked(void) ;
#line 379
extern int putc_unlocked(int  , FILE * ) ;
#line 380
extern int putchar_unlocked(int  ) ;
#line 384
extern int getw(FILE * ) ;
#line 385
extern int putw(int  , FILE * ) ;
#line 389
extern char __attribute__((__deprecated__("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead.")))  *tempnam(char const   * ,
                                                                                                                                                                                                                                             char const   * )  __asm__("_tempnam")  ;
#line 414
extern int fseeko(FILE * , off_t  , int  ) ;
#line 415
extern off_t ftello(FILE * ) ;
#line 421
extern int ( /* format attribute */  snprintf)(char * __restrict   , size_t  , char const   * __restrict   
                                               , ...) ;
#line 422
extern int ( /* format attribute */  vfscanf)(FILE * __restrict   , char const   * __restrict   ,
                                              va_list  ) ;
#line 423
extern int ( /* format attribute */  vscanf)(char const   * __restrict   , va_list  ) ;
#line 424
extern int ( /* format attribute */  vsnprintf)(char * __restrict   , size_t  , char const   * __restrict   ,
                                                va_list  ) ;
#line 425
extern int ( /* format attribute */  vsscanf)(char const   * __restrict   , char const   * __restrict   ,
                                              va_list  ) ;
#line 439
extern int ( /* format attribute */  dprintf)(int  , char const   * __restrict   
                                              , ...) ;
#line 440
extern int ( /* format attribute */  vdprintf)(int  , char const   * __restrict   ,
                                               va_list  ) ;
#line 441
extern ssize_t getdelim(char ** __restrict   , size_t * __restrict   , int  , FILE * __restrict   ) ;
#line 442
extern ssize_t getline(char ** __restrict   , size_t * __restrict   , FILE * __restrict   ) ;
#line 452
extern int const   sys_nerr ;
#line 453
extern char const   * const  sys_errlist[] ;
#line 455
extern int ( /* format attribute */  asprintf)(char ** __restrict   , char const   * __restrict   
                                               , ...) ;
#line 456
extern char *ctermid_r(char * ) ;
#line 457
extern char *fgetln(FILE * , size_t * ) ;
#line 458
extern char const   *fmtcheck(char const   * , char const   * ) ;
#line 459
extern int fpurge(FILE * ) ;
#line 460
extern void setbuffer(FILE * , char * , int  ) ;
#line 461
extern int setlinebuf(FILE * ) ;
#line 462
extern int ( /* format attribute */  vasprintf)(char ** __restrict   , char const   * __restrict   ,
                                                va_list  ) ;
#line 463
extern FILE *zopen(char const   * , char const   * , int  ) ;
#line 469
extern FILE *funopen(void const   * , int (*)(void * , char * , int  ) , int (*)(void * ,
                                                                                 char const   * ,
                                                                                 int  ) ,
                     fpos_t (*)(void * , fpos_t  , int  ) , int (*)(void * ) ) ;
#line 42 "/usr/include/secure/_stdio.h"
extern int __sprintf_chk(char * __restrict   , int  , size_t  , char const   * __restrict   
                         , ...) ;
#line 52
extern int __snprintf_chk(char * __restrict   , size_t  , int  , size_t  , char const   * __restrict   
                          , ...) ;
#line 61
extern int __vsprintf_chk(char * __restrict   , int  , size_t  , char const   * __restrict   ,
                          va_list  ) ;
#line 70
extern int __vsnprintf_chk(char * __restrict   , size_t  , int  , size_t  , char const   * __restrict   ,
                           va_list  ) ;
#line 3 "simple.c"
int main(void) 
{ 
  int x ;
  int y ;

  {
#line 4
  x = 1;
#line 5
  y = 2;
#line 6
  return (x + y);
}
}
void print_hello(void) 
{ 


  {
  printf("Hello World\n");
}
}
