/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void *_memoize[4096] ;
int _memoizeMax ;
void malloc ;
int read(int fd , void *buf , int count ) ;
int write(int fd , void *buf , int count ) ;
int close(int fd ) ;
void open ;
#line 5 "ap_mission.i"
typedef char bool;
#line 6 "ap_mission.i"
typedef unsigned char __uint8_t;
#line 7 "ap_mission.i"
typedef short __int16_t;
#line 8 "ap_mission.i"
typedef unsigned short __uint16_t;
#line 9 "ap_mission.i"
typedef int __int32_t;
#line 10 "ap_mission.i"
typedef unsigned int __uint32_t;
#line 11 "ap_mission.i"
typedef long long __int64_t;
#line 12 "ap_mission.i"
typedef unsigned long long __uint64_t;
#line 13 "ap_mission.i"
typedef signed char int8_t;
#line 14 "ap_mission.i"
typedef short int16_t;
#line 15 "ap_mission.i"
typedef int int32_t;
#line 16 "ap_mission.i"
typedef long long int64_t;
#line 17 "ap_mission.i"
typedef unsigned char uint8_t;
#line 18 "ap_mission.i"
typedef unsigned short uint16_t;
#line 19 "ap_mission.i"
typedef unsigned int uint32_t;
#line 20 "ap_mission.i"
typedef unsigned long long uint64_t;
#line 23 "ap_mission.i"
struct ahrs_flags {
   uint8_t have_initial_yaw : 1 ;
   uint8_t fly_forward : 1 ;
   uint8_t correct_centrifugal : 1 ;
   uint8_t wind_estimation : 1 ;
   uint8_t likely_flying : 1 ;
};
#line 23 "ap_mission.i"
struct AP_AHRS {
   float roll ;
   float pitch ;
   float yaw ;
   int32_t roll_sensor ;
   int32_t pitch_sensor ;
   int32_t yaw_sensor ;
   float _kp_yaw ;
   float _kp ;
   float gps_gain ;
   float beta ;
   int8_t _gps_use ;
   int8_t _wind_max ;
   int8_t _board_orientation ;
   int8_t _gps_minsats ;
   int8_t _gps_delay ;
   int8_t _ekf_type ;
   struct ahrs_flags _flags ;
   uint32_t _last_flying_ms ;
   uint32_t _compass_last_update ;
   float _gyro_drift_limit ;
   float _cos_roll ;
   float _cos_pitch ;
   float _cos_yaw ;
   float _sin_roll ;
   float _sin_pitch ;
   float _sin_yaw ;
   uint8_t _active_accel_instance ;
   float _AOA ;
   float _SSA ;
   uint32_t _last_AOA_update_ms ;
};
#line 657 "ap_mission.i"
typedef struct AP_AHRS AP_AHRS;
#line 659
enum mission_state {
    MISSION_STOPPED = 0,
    MISSION_RUNNING = 1,
    MISSION_COMPLETE = 2
} ;
#line 665 "ap_mission.i"
typedef enum mission_state mission_state;
#line 672 "ap_mission.i"
struct Mission_Command {
   uint16_t index ;
   uint16_t id ;
   uint16_t p1 ;
};
#line 672 "ap_mission.i"
struct Mission_Flags {
   mission_state state ;
   uint8_t nav_cmd_loaded : 1 ;
   uint8_t do_cmd_loaded : 1 ;
   uint8_t do_cmd_all_done : 1 ;
};
#line 672 "ap_mission.i"
struct jump_tracking_struct {
   uint16_t index ;
   int16_t num_times_run ;
};
#line 672 "ap_mission.i"
struct AP_Mission {
   struct Mission_Command __annonCompField1 ;
   struct Mission_Flags _flags ;
   int16_t _cmd_total ;
   int8_t _restart ;
   int16_t _options ;
   struct Mission_Command _nav_cmd ;
   struct Mission_Command _do_cmd ;
   uint16_t _prev_nav_cmd_id ;
   uint16_t _prev_nav_cmd_index ;
   uint16_t _prev_nav_cmd_wp_index ;
   struct jump_tracking_struct _jump_tracking[15] ;
   uint32_t _last_change_time_ms ;
};
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
void __deserialize_scalarInt16(unsigned short *ptr , int fd ) ;
void __deserialize_array15_jump_tracking_struct(struct jump_tracking_struct (*ptr)[15] ,
                                                int fd ) ;
void __serialize_AP_Mission(struct AP_Mission *ptr , int fd ) ;
void __deserialize_mission_state(enum mission_state *ptr , int fd ) ;
void __serialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __deserialize_Mission_Flags(struct Mission_Flags *ptr , int fd ) ;
void __deserialize_Mission_Command(struct Mission_Command *ptr , int fd ) ;
void __serialize_array15_jump_tracking_struct(struct jump_tracking_struct (*ptr)[15] ,
                                              int fd ) ;
void __serialize_jump_tracking_struct(struct jump_tracking_struct *ptr , int fd ) ;
void __deserialize_scalarInt32(unsigned int *ptr , int fd ) ;
void __serialize_Mission_Command(struct Mission_Command *ptr , int fd ) ;
void __serialize_scalarInt32(unsigned int *ptr , int fd ) ;
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __serialize_Mission_Flags(struct Mission_Flags *ptr , int fd ) ;
void __serialize_mission_state(enum mission_state *ptr , int fd ) ;
void __deserialize_AP_Mission(struct AP_Mission *ptr , int fd ) ;
void __deserialize_jump_tracking_struct(struct jump_tracking_struct *ptr , int fd ) ;
void __serialize_scalarInt16(unsigned short *ptr , int fd ) ;
void __deserialize_scalarInt16(unsigned short *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 2);
}
}
void __deserialize_array15_jump_tracking_struct(struct jump_tracking_struct (*ptr)[15] ,
                                                int fd ) 
{ 
  int i3 ;

  {
  i3 = 0;
  while (i3 < 15) {
    {
    __deserialize_jump_tracking_struct(& (*ptr)[i3], fd);
    i3 ++;
    }
  }
}
}
void __serialize_AP_Mission(struct AP_Mission *ptr , int fd ) 
{ 


  {
  __serialize_Mission_Command((struct Mission_Command *)(& ptr->__annonCompField1),
                              fd);
  __serialize_Mission_Flags((struct Mission_Flags *)(& ptr->_flags), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->_cmd_total), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->_restart), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->_options), fd);
  __serialize_Mission_Command((struct Mission_Command *)(& ptr->_nav_cmd), fd);
  __serialize_Mission_Command((struct Mission_Command *)(& ptr->_do_cmd), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_id), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_index), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_wp_index), fd);
  __serialize_array15_jump_tracking_struct((struct jump_tracking_struct (*)[15])(& ptr->_jump_tracking),
                                           fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->_last_change_time_ms), fd);
}
}
void __deserialize_mission_state(enum mission_state *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 1);
}
}
void __deserialize_Mission_Flags(struct Mission_Flags *ptr , int fd ) 
{ 


  {
  __deserialize_mission_state((enum mission_state *)(& ptr->state), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->nav_cmd_loaded), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->do_cmd_loaded), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->do_cmd_all_done), fd);
}
}
void __deserialize_Mission_Command(struct Mission_Command *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt16((unsigned short *)(& ptr->index), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->id), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->p1), fd);
}
}
void __serialize_array15_jump_tracking_struct(struct jump_tracking_struct (*ptr)[15] ,
                                              int fd ) 
{ 
  int i3 ;

  {
  i3 = 0;
  while (i3 < 15) {
    {
    __serialize_jump_tracking_struct(& (*ptr)[i3], fd);
    i3 ++;
    }
  }
}
}
void __serialize_jump_tracking_struct(struct jump_tracking_struct *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt16((unsigned short *)(& ptr->index), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->num_times_run), fd);
}
}
void __deserialize_scalarInt32(unsigned int *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_Mission_Command(struct Mission_Command *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt16((unsigned short *)(& ptr->index), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->id), fd);
  __serialize_scalarInt16((unsigned short *)(& ptr->p1), fd);
}
}
void __serialize_scalarInt32(unsigned int *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 1);
}
}
void __serialize_Mission_Flags(struct Mission_Flags *ptr , int fd ) 
{ 


  {
  __serialize_mission_state((enum mission_state *)(& ptr->state), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->nav_cmd_loaded), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->do_cmd_loaded), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->do_cmd_all_done), fd);
}
}
void __serialize_mission_state(enum mission_state *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_AP_Mission(struct AP_Mission *ptr , int fd ) 
{ 


  {
  __deserialize_Mission_Command((struct Mission_Command *)(& ptr->__annonCompField1),
                                fd);
  __deserialize_Mission_Flags((struct Mission_Flags *)(& ptr->_flags), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->_cmd_total), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->_restart), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->_options), fd);
  __deserialize_Mission_Command((struct Mission_Command *)(& ptr->_nav_cmd), fd);
  __deserialize_Mission_Command((struct Mission_Command *)(& ptr->_do_cmd), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_id), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_index), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->_prev_nav_cmd_wp_index), fd);
  __deserialize_array15_jump_tracking_struct((struct jump_tracking_struct (*)[15])(& ptr->_jump_tracking),
                                             fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->_last_change_time_ms), fd);
}
}
void __deserialize_jump_tracking_struct(struct jump_tracking_struct *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt16((unsigned short *)(& ptr->index), fd);
  __deserialize_scalarInt16((unsigned short *)(& ptr->num_times_run), fd);
}
}
void __serialize_scalarInt16(unsigned short *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 2);
}
}
#line 1189 "ap_mission.i"
int main(void) 
{ 
  struct AP_Mission myApMission ;
  int fd2 ;
  int fd3 ;

  {
  {
  SERIALIZE: ;
  {
  fd2 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __serialize_AP_Mission(& myApMission, fd2);
  close(fd2);
  }
  }
  {
  DESERIALIZE: ;
  {
  fd3 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __deserialize_AP_Mission(& myApMission, fd3);
  close(fd3);
  }
  }
#line 1200
  return (0);
}
}
