/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void *_memoize[4096] ;
int _memoizeMax ;
void malloc ;
int read(int fd , void *buf , int count ) ;
int write(int fd , void *buf , int count ) ;
int close(int fd ) ;
void open ;
#line 1 "yu.i"
typedef char bool;
#line 2 "yu.i"
typedef unsigned char __uint8_t;
#line 3 "yu.i"
typedef short __int16_t;
#line 4 "yu.i"
typedef unsigned short __uint16_t;
#line 5 "yu.i"
typedef int __int32_t;
#line 6 "yu.i"
typedef unsigned int __uint32_t;
#line 7 "yu.i"
typedef long long __int64_t;
#line 8 "yu.i"
typedef unsigned long long __uint64_t;
#line 9 "yu.i"
typedef signed char int8_t;
#line 10 "yu.i"
typedef short int16_t;
#line 11 "yu.i"
typedef int int32_t;
#line 12 "yu.i"
typedef long long int64_t;
#line 13 "yu.i"
typedef unsigned char uint8_t;
#line 14 "yu.i"
typedef unsigned short uint16_t;
#line 15 "yu.i"
typedef unsigned int uint32_t;
#line 16 "yu.i"
typedef unsigned long long uint64_t;
#line 17 "yu.i"
struct __anonstruct_heli_flags_t_1 {
   uint8_t dynamic_flight : 1 ;
   uint8_t init_targets_on_arming : 1 ;
   uint8_t inverted_flight : 1 ;
};
#line 17 "yu.i"
typedef struct __anonstruct_heli_flags_t_1 heli_flags_t;
#line 25 "yu.i"
struct __anonstruct_takeoff_state_t_2 {
   bool running ;
   float max_speed ;
   float alt_delta ;
   uint32_t start_ms ;
};
#line 25 "yu.i"
typedef struct __anonstruct_takeoff_state_t_2 takeoff_state_t;
#line 33
enum HomeState {
    HOME_UNSET = 0,
    HOME_SET_NOT_LOCKED = 1,
    HOME_SET_AND_LOCKED = 2
} ;
#line 38 "yu.i"
typedef enum HomeState HomeState;
#line 40
enum control_mode_t {
    STABILIZE = 0,
    ACRO = 1,
    ALT_HOLD = 2,
    AUTO = 3,
    GUIDED = 4,
    LOITER = 5,
    RTL = 6,
    CIRCLE = 7,
    LAND = 9,
    DRIFT = 11,
    SPORT = 13,
    FLIP = 14,
    AUTOTUNE = 15,
    POSHOLD = 16,
    BRAKE = 17,
    THROW = 18,
    AVOID_ADSB = 19,
    GUIDED_NOGPS = 20,
    SMART_RTL = 21
} ;
#line 61 "yu.i"
typedef enum control_mode_t control_mode_t;
#line 63
enum mode_reason_t {
    MODE_REASON_UNKNOWN = 0,
    MODE_REASON_TX_COMMAND = 1,
    MODE_REASON_GCS_COMMAND = 2,
    MODE_REASON_RADIO_FAILSAFE = 3,
    MODE_REASON_BATTERY_FAILSAFE = 4,
    MODE_REASON_GCS_FAILSAFE = 5,
    MODE_REASON_EKF_FAILSAFE = 6,
    MODE_REASON_GPS_GLITCH = 7,
    MODE_REASON_MISSION_END = 8,
    MODE_REASON_THROTTLE_LAND_ESCAPE = 9,
    MODE_REASON_FENCE_BREACH = 10,
    MODE_REASON_TERRAIN_FAILSAFE = 11,
    MODE_REASON_BRAKE_TIMEOUT = 12,
    MODE_REASON_FLIP_COMPLETE = 13,
    MODE_REASON_AVOIDANCE = 14,
    MODE_REASON_AVOIDANCE_RECOVERY = 15,
    MODE_REASON_THROW_COMPLETE = 16,
    MODE_REASON_TERMINATE = 17
} ;
#line 83 "yu.i"
typedef enum mode_reason_t mode_reason_t;
#line 111 "yu.i"
struct __anonstruct_rangefinder_state_3 {
   bool enabled : 1 ;
   bool alt_healthy : 1 ;
   int16_t alt_cm ;
   uint32_t last_healthy_ms ;
   int8_t glitch_count ;
};
#line 111 "yu.i"
struct __anonstruct____missing_field_name_5 {
   uint8_t unused1 : 1 ;
   uint8_t simple_mode : 2 ;
   uint8_t pre_arm_rc_check : 1 ;
   uint8_t pre_arm_check : 1 ;
   uint8_t auto_armed : 1 ;
   uint8_t logging_started : 1 ;
   uint8_t land_complete : 1 ;
   uint8_t new_radio_frame : 1 ;
   uint8_t usb_connected : 1 ;
   uint8_t rc_receiver_present : 1 ;
   uint8_t compass_mot : 1 ;
   uint8_t motor_test : 1 ;
   uint8_t initialised : 1 ;
   uint8_t land_complete_maybe : 1 ;
   uint8_t throttle_zero : 1 ;
   uint8_t system_time_set : 1 ;
   uint8_t gps_glitching : 1 ;
   enum HomeState home_state : 2 ;
   uint8_t using_interlock : 1 ;
   uint8_t motor_emergency_stop : 1 ;
   uint8_t land_repo_active : 1 ;
   uint8_t motor_interlock_switch : 1 ;
   uint8_t in_arming_delay : 1 ;
   uint8_t initialised_params : 1 ;
   uint8_t compass_init_location : 1 ;
};
#line 111 "yu.i"
union __anonunion_ap_t_4 {
   struct __anonstruct____missing_field_name_5 __annonCompField1 ;
   uint32_t value ;
};
#line 111 "yu.i"
struct __anonstruct_control_switch_state_6 {
   int8_t debounced_switch_position ;
   int8_t last_switch_position ;
   uint32_t last_edge_time_ms ;
};
#line 111 "yu.i"
struct __anonstruct_failsafe_7 {
   uint8_t rc_override_active : 1 ;
   uint8_t radio : 1 ;
   uint8_t battery : 1 ;
   uint8_t gcs : 1 ;
   uint8_t ekf : 1 ;
   uint8_t terrain : 1 ;
   uint8_t adsb : 1 ;
   int8_t radio_counter ;
   uint32_t last_heartbeat_ms ;
   uint32_t terrain_first_failure_ms ;
   uint32_t terrain_last_failure_ms ;
};
#line 111 "yu.i"
struct __anonstruct_sensor_health_8 {
   uint8_t baro : 1 ;
   uint8_t compass : 1 ;
   uint8_t primary_gps ;
};
#line 111 "yu.i"
struct __anonstruct_gndeffect_state_9 {
   bool takeoff_expected ;
   bool touchdown_expected ;
   uint32_t takeoff_time_ms ;
   float takeoff_alt_cm ;
};
#line 111 "yu.i"
struct Copter {
   uint8_t command_ack_counter ;
   struct __anonstruct_rangefinder_state_3 rangefinder_state ;
   float ekfGndSpdLimit ;
   float ekfNavVelGainScaler ;
   int8_t ekf_primary_core ;
   union __anonunion_ap_t_4 ap_t ;
   control_mode_t control_mode ;
   mode_reason_t control_mode_reason ;
   control_mode_t prev_control_mode ;
   mode_reason_t prev_control_mode_reason ;
   struct __anonstruct_control_switch_state_6 control_switch_state ;
   float auto_takeoff_no_nav_alt_cm ;
   uint8_t receiver_rssi ;
   struct __anonstruct_failsafe_7 failsafe ;
   struct __anonstruct_sensor_health_8 sensor_health ;
   float scaleLongDown ;
   int32_t _home_bearing ;
   uint32_t _home_distance ;
   float simple_cos_yaw ;
   float simple_sin_yaw ;
   int32_t super_simple_last_bearing ;
   float super_simple_cos_yaw ;
   float super_simple_sin_yaw ;
   int32_t initial_armed_bearing ;
   uint32_t control_sensors_present ;
   uint32_t control_sensors_enabled ;
   uint32_t control_sensors_health ;
   int16_t climb_rate ;
   float target_rangefinder_alt ;
   int32_t baro_alt ;
   float baro_climbrate ;
   uint8_t auto_yaw_mode ;
   float yaw_look_at_WP_bearing ;
   int32_t yaw_look_at_heading ;
   int16_t yaw_look_at_heading_slew ;
   float yaw_look_ahead_bearing ;
   float auto_yaw_rate_cds ;
   float G_Dt ;
   int16_t pmTest1 ;
   uint32_t fast_loopTimer ;
   uint16_t mainLoop_count ;
   uint32_t arm_time_ms ;
   uint8_t auto_trim_counter ;
   bool in_mavlink_delay ;
   uint32_t last_radio_update_ms ;
   uint32_t esc_calibration_notify_update_ms ;
   uint32_t visual_odom_last_update_ms ;
   int16_t hover_roll_trim_scalar_slew ;
   struct __anonstruct_gndeffect_state_9 gndeffect_state ;
   bool upgrading_frame_params ;
};
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
#line 22 "yu.i"
heli_flags_t heli_flags  ;
#line 31 "yu.i"
takeoff_state_t takeoff_state  ;
void __deserialize___anonstruct_rangefinder_state_3(struct __anonstruct_rangefinder_state_3 *ptr ,
                                                    int fd ) ;
void __serialize___anonstruct_gndeffect_state_9(struct __anonstruct_gndeffect_state_9 *ptr ,
                                                int fd ) ;
void __deserialize_scalarInt16(short *ptr , int fd ) ;
void __deserialize___anonstruct_sensor_health_8(struct __anonstruct_sensor_health_8 *ptr ,
                                                int fd ) ;
void __serialize_control_mode_t(enum control_mode_t *ptr , int fd ) ;
void __serialize___anonstruct_sensor_health_8(struct __anonstruct_sensor_health_8 *ptr ,
                                              int fd ) ;
void __deserialize_scalarFloat32(float *ptr , int fd ) ;
void __serialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __serialize___anonstruct_rangefinder_state_3(struct __anonstruct_rangefinder_state_3 *ptr ,
                                                  int fd ) ;
void __deserialize___anonstruct_control_switch_state_6(struct __anonstruct_control_switch_state_6 *ptr ,
                                                       int fd ) ;
void __serialize_Copter(struct Copter *ptr , int fd ) ;
void __serialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) ;
void __deserialize___anonstruct_gndeffect_state_9(struct __anonstruct_gndeffect_state_9 *ptr ,
                                                  int fd ) ;
void __deserialize_control_mode_t(enum control_mode_t *ptr , int fd ) ;
void __deserialize_Copter(struct Copter *ptr , int fd ) ;
void __deserialize_HomeState(enum HomeState *ptr , int fd ) ;
void __serialize___anonstruct_failsafe_7(struct __anonstruct_failsafe_7 *ptr , int fd ) ;
void __deserialize_scalarInt32(unsigned int *ptr , int fd ) ;
void __serialize_scalarFloat32(float *ptr , int fd ) ;
void __deserialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) ;
void __serialize_scalarInt32(unsigned int *ptr , int fd ) ;
void __deserialize___anonunion_ap_t_4(union __anonunion_ap_t_4 *ptr , int fd ) ;
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __serialize___anonunion_ap_t_4(union __anonunion_ap_t_4 *ptr , int fd ) ;
void __deserialize___anonstruct____missing_field_name_5(struct __anonstruct____missing_field_name_5 *ptr ,
                                                        int fd ) ;
void __serialize_scalarInt16(short *ptr , int fd ) ;
void __serialize_HomeState(enum HomeState *ptr , int fd ) ;
void __serialize___anonstruct_control_switch_state_6(struct __anonstruct_control_switch_state_6 *ptr ,
                                                     int fd ) ;
void __deserialize___anonstruct_failsafe_7(struct __anonstruct_failsafe_7 *ptr , int fd ) ;
void __serialize___anonstruct____missing_field_name_5(struct __anonstruct____missing_field_name_5 *ptr ,
                                                      int fd ) ;
void __deserialize___anonstruct_rangefinder_state_3(struct __anonstruct_rangefinder_state_3 *ptr ,
                                                    int fd ) 
{ 


  {

}
}
void __serialize___anonstruct_gndeffect_state_9(struct __anonstruct_gndeffect_state_9 *ptr ,
                                                int fd ) 
{ 


  {

}
}
void __deserialize_scalarInt16(short *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 2);
}
}
void __deserialize___anonstruct_sensor_health_8(struct __anonstruct_sensor_health_8 *ptr ,
                                                int fd ) 
{ 


  {

}
}
void __serialize_control_mode_t(enum control_mode_t *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize___anonstruct_sensor_health_8(struct __anonstruct_sensor_health_8 *ptr ,
                                              int fd ) 
{ 


  {

}
}
void __deserialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 1);
}
}
void __serialize___anonstruct_rangefinder_state_3(struct __anonstruct_rangefinder_state_3 *ptr ,
                                                  int fd ) 
{ 


  {

}
}
void __deserialize___anonstruct_control_switch_state_6(struct __anonstruct_control_switch_state_6 *ptr ,
                                                       int fd ) 
{ 


  {

}
}
void __serialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt8((unsigned char *)(& ptr->command_ack_counter), fd);
  __serialize___anonstruct_rangefinder_state_3((struct __anonstruct_rangefinder_state_3 *)(& ptr->rangefinder_state),
                                               fd);
  __serialize_scalarFloat32((float *)(& ptr->ekfGndSpdLimit), fd);
  __serialize_scalarFloat32((float *)(& ptr->ekfNavVelGainScaler), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->ekf_primary_core), fd);
  __serialize___anonunion_ap_t_4((union __anonunion_ap_t_4 *)(& ptr->ap_t), fd);
  __serialize_control_mode_t((enum control_mode_t *)(& ptr->control_mode), fd);
  __serialize_mode_reason_t((enum mode_reason_t *)(& ptr->control_mode_reason), fd);
  __serialize_control_mode_t((enum control_mode_t *)(& ptr->prev_control_mode), fd);
  __serialize_mode_reason_t((enum mode_reason_t *)(& ptr->prev_control_mode_reason),
                            fd);
  __serialize___anonstruct_control_switch_state_6((struct __anonstruct_control_switch_state_6 *)(& ptr->control_switch_state),
                                                  fd);
  __serialize_scalarFloat32((float *)(& ptr->auto_takeoff_no_nav_alt_cm), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->receiver_rssi), fd);
  __serialize___anonstruct_failsafe_7((struct __anonstruct_failsafe_7 *)(& ptr->failsafe),
                                      fd);
  __serialize___anonstruct_sensor_health_8((struct __anonstruct_sensor_health_8 *)(& ptr->sensor_health),
                                           fd);
  __serialize_scalarFloat32((float *)(& ptr->scaleLongDown), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->_home_bearing), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->_home_distance), fd);
  __serialize_scalarFloat32((float *)(& ptr->simple_cos_yaw), fd);
  __serialize_scalarFloat32((float *)(& ptr->simple_sin_yaw), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->super_simple_last_bearing), fd);
  __serialize_scalarFloat32((float *)(& ptr->super_simple_cos_yaw), fd);
  __serialize_scalarFloat32((float *)(& ptr->super_simple_sin_yaw), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->initial_armed_bearing), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->control_sensors_present), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->control_sensors_enabled), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->control_sensors_health), fd);
  __serialize_scalarInt16((short *)(& ptr->climb_rate), fd);
  __serialize_scalarFloat32((float *)(& ptr->target_rangefinder_alt), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->baro_alt), fd);
  __serialize_scalarFloat32((float *)(& ptr->baro_climbrate), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->auto_yaw_mode), fd);
  __serialize_scalarFloat32((float *)(& ptr->yaw_look_at_WP_bearing), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->yaw_look_at_heading), fd);
  __serialize_scalarInt16((short *)(& ptr->yaw_look_at_heading_slew), fd);
  __serialize_scalarFloat32((float *)(& ptr->yaw_look_ahead_bearing), fd);
  __serialize_scalarFloat32((float *)(& ptr->auto_yaw_rate_cds), fd);
  __serialize_scalarFloat32((float *)(& ptr->G_Dt), fd);
  __serialize_scalarInt16((short *)(& ptr->pmTest1), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->fast_loopTimer), fd);
  __serialize_scalarInt16((short *)(& ptr->mainLoop_count), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->arm_time_ms), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->auto_trim_counter), fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->in_mavlink_delay), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->last_radio_update_ms), fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->esc_calibration_notify_update_ms),
                          fd);
  __serialize_scalarInt32((unsigned int *)(& ptr->visual_odom_last_update_ms), fd);
  __serialize_scalarInt16((short *)(& ptr->hover_roll_trim_scalar_slew), fd);
  __serialize___anonstruct_gndeffect_state_9((struct __anonstruct_gndeffect_state_9 *)(& ptr->gndeffect_state),
                                             fd);
  __serialize_scalarInt8((unsigned char *)(& ptr->upgrading_frame_params), fd);
}
}
void __serialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize___anonstruct_gndeffect_state_9(struct __anonstruct_gndeffect_state_9 *ptr ,
                                                  int fd ) 
{ 


  {

}
}
void __deserialize_control_mode_t(enum control_mode_t *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt8((unsigned char *)(& ptr->command_ack_counter), fd);
  __deserialize___anonstruct_rangefinder_state_3((struct __anonstruct_rangefinder_state_3 *)(& ptr->rangefinder_state),
                                                 fd);
  __deserialize_scalarFloat32((float *)(& ptr->ekfGndSpdLimit), fd);
  __deserialize_scalarFloat32((float *)(& ptr->ekfNavVelGainScaler), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->ekf_primary_core), fd);
  __deserialize___anonunion_ap_t_4((union __anonunion_ap_t_4 *)(& ptr->ap_t), fd);
  __deserialize_control_mode_t((enum control_mode_t *)(& ptr->control_mode), fd);
  __deserialize_mode_reason_t((enum mode_reason_t *)(& ptr->control_mode_reason),
                              fd);
  __deserialize_control_mode_t((enum control_mode_t *)(& ptr->prev_control_mode),
                               fd);
  __deserialize_mode_reason_t((enum mode_reason_t *)(& ptr->prev_control_mode_reason),
                              fd);
  __deserialize___anonstruct_control_switch_state_6((struct __anonstruct_control_switch_state_6 *)(& ptr->control_switch_state),
                                                    fd);
  __deserialize_scalarFloat32((float *)(& ptr->auto_takeoff_no_nav_alt_cm), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->receiver_rssi), fd);
  __deserialize___anonstruct_failsafe_7((struct __anonstruct_failsafe_7 *)(& ptr->failsafe),
                                        fd);
  __deserialize___anonstruct_sensor_health_8((struct __anonstruct_sensor_health_8 *)(& ptr->sensor_health),
                                             fd);
  __deserialize_scalarFloat32((float *)(& ptr->scaleLongDown), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->_home_bearing), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->_home_distance), fd);
  __deserialize_scalarFloat32((float *)(& ptr->simple_cos_yaw), fd);
  __deserialize_scalarFloat32((float *)(& ptr->simple_sin_yaw), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->super_simple_last_bearing), fd);
  __deserialize_scalarFloat32((float *)(& ptr->super_simple_cos_yaw), fd);
  __deserialize_scalarFloat32((float *)(& ptr->super_simple_sin_yaw), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->initial_armed_bearing), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->control_sensors_present), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->control_sensors_enabled), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->control_sensors_health), fd);
  __deserialize_scalarInt16((short *)(& ptr->climb_rate), fd);
  __deserialize_scalarFloat32((float *)(& ptr->target_rangefinder_alt), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->baro_alt), fd);
  __deserialize_scalarFloat32((float *)(& ptr->baro_climbrate), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->auto_yaw_mode), fd);
  __deserialize_scalarFloat32((float *)(& ptr->yaw_look_at_WP_bearing), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->yaw_look_at_heading), fd);
  __deserialize_scalarInt16((short *)(& ptr->yaw_look_at_heading_slew), fd);
  __deserialize_scalarFloat32((float *)(& ptr->yaw_look_ahead_bearing), fd);
  __deserialize_scalarFloat32((float *)(& ptr->auto_yaw_rate_cds), fd);
  __deserialize_scalarFloat32((float *)(& ptr->G_Dt), fd);
  __deserialize_scalarInt16((short *)(& ptr->pmTest1), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->fast_loopTimer), fd);
  __deserialize_scalarInt16((short *)(& ptr->mainLoop_count), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->arm_time_ms), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->auto_trim_counter), fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->in_mavlink_delay), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->last_radio_update_ms), fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->esc_calibration_notify_update_ms),
                            fd);
  __deserialize_scalarInt32((unsigned int *)(& ptr->visual_odom_last_update_ms), fd);
  __deserialize_scalarInt16((short *)(& ptr->hover_roll_trim_scalar_slew), fd);
  __deserialize___anonstruct_gndeffect_state_9((struct __anonstruct_gndeffect_state_9 *)(& ptr->gndeffect_state),
                                               fd);
  __deserialize_scalarInt8((unsigned char *)(& ptr->upgrading_frame_params), fd);
}
}
void __deserialize_HomeState(enum HomeState *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize___anonstruct_failsafe_7(struct __anonstruct_failsafe_7 *ptr , int fd ) 
{ 


  {

}
}
void __deserialize_scalarInt32(unsigned int *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarInt32(unsigned int *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize___anonunion_ap_t_4(union __anonunion_ap_t_4 *ptr , int fd ) 
{ 


  {

}
}
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 1);
}
}
void __serialize___anonunion_ap_t_4(union __anonunion_ap_t_4 *ptr , int fd ) 
{ 


  {

}
}
void __deserialize___anonstruct____missing_field_name_5(struct __anonstruct____missing_field_name_5 *ptr ,
                                                        int fd ) 
{ 


  {

}
}
void __serialize_scalarInt16(short *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 2);
}
}
void __serialize_HomeState(enum HomeState *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize___anonstruct_control_switch_state_6(struct __anonstruct_control_switch_state_6 *ptr ,
                                                     int fd ) 
{ 


  {

}
}
void __deserialize___anonstruct_failsafe_7(struct __anonstruct_failsafe_7 *ptr , int fd ) 
{ 


  {

}
}
void __serialize___anonstruct____missing_field_name_5(struct __anonstruct____missing_field_name_5 *ptr ,
                                                      int fd ) 
{ 


  {

}
}
#line 1896 "yu.i"
int main(void) 
{ 
  struct Copter myCopter ;
  int fd2 ;
  int fd3 ;

  {
  {
  SERIALIZE: ;
  {
  fd2 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __serialize_Copter(& myCopter, fd2);
  close(fd2);
  }
  }
  {
  DESERIALIZE: ;
  {
  fd3 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __deserialize_Copter(& myCopter, fd3);
  close(fd3);
  }
  }
#line 1905
  return (0);
}
}
