/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void *_memoize[4096] ;
int _memoizeMax ;
#line 37 "/usr/include/i386/_types.h"
typedef signed char __int8_t;
#line 41 "/usr/include/i386/_types.h"
typedef unsigned char __uint8_t;
#line 42 "/usr/include/i386/_types.h"
typedef short __int16_t;
#line 43 "/usr/include/i386/_types.h"
typedef unsigned short __uint16_t;
#line 44 "/usr/include/i386/_types.h"
typedef int __int32_t;
#line 45 "/usr/include/i386/_types.h"
typedef unsigned int __uint32_t;
#line 46 "/usr/include/i386/_types.h"
typedef long long __int64_t;
#line 47 "/usr/include/i386/_types.h"
typedef unsigned long long __uint64_t;
#line 49 "/usr/include/i386/_types.h"
typedef long __darwin_intptr_t;
#line 50 "/usr/include/i386/_types.h"
typedef unsigned int __darwin_natural_t;
#line 70 "/usr/include/i386/_types.h"
typedef int __darwin_ct_rune_t;
#line 76 "/usr/include/i386/_types.h"
union __anonunion___mbstate_t_1 {
   char __mbstate8[128] ;
   long long _mbstateL ;
};
#line 76 "/usr/include/i386/_types.h"
typedef union __anonunion___mbstate_t_1 __mbstate_t;
#line 81 "/usr/include/i386/_types.h"
typedef __mbstate_t __darwin_mbstate_t;
#line 84 "/usr/include/i386/_types.h"
typedef long __darwin_ptrdiff_t;
#line 92 "/usr/include/i386/_types.h"
typedef unsigned long __darwin_size_t;
#line 98 "/usr/include/i386/_types.h"
typedef __builtin_va_list __darwin_va_list;
#line 104 "/usr/include/i386/_types.h"
typedef int __darwin_wchar_t;
#line 109 "/usr/include/i386/_types.h"
typedef __darwin_wchar_t __darwin_rune_t;
#line 112 "/usr/include/i386/_types.h"
typedef int __darwin_wint_t;
#line 117 "/usr/include/i386/_types.h"
typedef unsigned long __darwin_clock_t;
#line 118 "/usr/include/i386/_types.h"
typedef __uint32_t __darwin_socklen_t;
#line 119 "/usr/include/i386/_types.h"
typedef long __darwin_ssize_t;
#line 120 "/usr/include/i386/_types.h"
typedef long __darwin_time_t;
#line 55 "/usr/include/sys/_types.h"
typedef __int64_t __darwin_blkcnt_t;
#line 56 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_blksize_t;
#line 57 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_dev_t;
#line 58 "/usr/include/sys/_types.h"
typedef unsigned int __darwin_fsblkcnt_t;
#line 59 "/usr/include/sys/_types.h"
typedef unsigned int __darwin_fsfilcnt_t;
#line 60 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_gid_t;
#line 61 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_id_t;
#line 62 "/usr/include/sys/_types.h"
typedef __uint64_t __darwin_ino64_t;
#line 64 "/usr/include/sys/_types.h"
typedef __darwin_ino64_t __darwin_ino_t;
#line 68 "/usr/include/sys/_types.h"
typedef __darwin_natural_t __darwin_mach_port_name_t;
#line 69 "/usr/include/sys/_types.h"
typedef __darwin_mach_port_name_t __darwin_mach_port_t;
#line 70 "/usr/include/sys/_types.h"
typedef __uint16_t __darwin_mode_t;
#line 71 "/usr/include/sys/_types.h"
typedef __int64_t __darwin_off_t;
#line 72 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_pid_t;
#line 73 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_sigset_t;
#line 74 "/usr/include/sys/_types.h"
typedef __int32_t __darwin_suseconds_t;
#line 75 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_uid_t;
#line 76 "/usr/include/sys/_types.h"
typedef __uint32_t __darwin_useconds_t;
#line 77 "/usr/include/sys/_types.h"
typedef unsigned char __darwin_uuid_t[16];
#line 78 "/usr/include/sys/_types.h"
typedef char __darwin_uuid_string_t[37];
#line 57 "/usr/include/sys/_pthread/_pthread_types.h"
struct __darwin_pthread_handler_rec {
   void (*__routine)(void * ) ;
   void *__arg ;
   struct __darwin_pthread_handler_rec *__next ;
};
#line 63 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_attr_t {
   long __sig ;
   char __opaque[56] ;
};
#line 68 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_cond_t {
   long __sig ;
   char __opaque[40] ;
};
#line 73 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_condattr_t {
   long __sig ;
   char __opaque[8] ;
};
#line 78 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_mutex_t {
   long __sig ;
   char __opaque[56] ;
};
#line 83 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_mutexattr_t {
   long __sig ;
   char __opaque[8] ;
};
#line 88 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_once_t {
   long __sig ;
   char __opaque[8] ;
};
#line 93 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_rwlock_t {
   long __sig ;
   char __opaque[192] ;
};
#line 98 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_rwlockattr_t {
   long __sig ;
   char __opaque[16] ;
};
#line 103 "/usr/include/sys/_pthread/_pthread_types.h"
struct _opaque_pthread_t {
   long __sig ;
   struct __darwin_pthread_handler_rec *__cleanup_stack ;
   char __opaque[8176] ;
};
#line 109 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_attr_t __darwin_pthread_attr_t;
#line 110 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_cond_t __darwin_pthread_cond_t;
#line 111 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_condattr_t __darwin_pthread_condattr_t;
#line 112 "/usr/include/sys/_pthread/_pthread_types.h"
typedef unsigned long __darwin_pthread_key_t;
#line 113 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_mutex_t __darwin_pthread_mutex_t;
#line 114 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_mutexattr_t __darwin_pthread_mutexattr_t;
#line 115 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_once_t __darwin_pthread_once_t;
#line 116 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_rwlock_t __darwin_pthread_rwlock_t;
#line 117 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_rwlockattr_t __darwin_pthread_rwlockattr_t;
#line 118 "/usr/include/sys/_pthread/_pthread_types.h"
typedef struct _opaque_pthread_t *__darwin_pthread_t;
#line 39 "/usr/include/_types.h"
typedef int __darwin_nl_item;
#line 40 "/usr/include/_types.h"
typedef int __darwin_wctrans_t;
#line 42 "/usr/include/_types.h"
typedef __uint32_t __darwin_wctype_t;
#line 31 "/usr/include/sys/_types/_va_list.h"
typedef __darwin_va_list va_list;
#line 30 "/usr/include/sys/_types/_size_t.h"
typedef __darwin_size_t size_t;
#line 77 "/usr/include/stdio.h"
typedef __darwin_off_t fpos_t;
#line 88 "/usr/include/stdio.h"
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
#line 94
struct __sFILEX;
#line 94
struct __sFILEX;
#line 122 "/usr/include/stdio.h"
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (*_close)(void * ) ;
   int (*_read)(void * , char * , int  ) ;
   fpos_t (*_seek)(void * , fpos_t  , int  ) ;
   int (*_write)(void * , char const   * , int  ) ;
   struct __sbuf _ub ;
   struct __sFILEX *_extra ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
#line 122 "/usr/include/stdio.h"
typedef struct __sFILE FILE;
#line 30 "/usr/include/sys/_types/_off_t.h"
typedef __darwin_off_t off_t;
#line 30 "/usr/include/sys/_types/_ssize_t.h"
typedef __darwin_ssize_t ssize_t;
#line 79 "/usr/include/sys/wait.h"
enum __anonenum_idtype_t_2 {
    P_ALL = 0,
    P_PID = 1,
    P_PGID = 2
} ;
#line 79 "/usr/include/sys/wait.h"
typedef enum __anonenum_idtype_t_2 idtype_t;
#line 30 "/usr/include/sys/_types/_pid_t.h"
typedef __darwin_pid_t pid_t;
#line 30 "/usr/include/sys/_types/_id_t.h"
typedef __darwin_id_t id_t;
#line 39 "/usr/include/i386/signal.h"
typedef int sig_atomic_t;
#line 43 "/usr/include/mach/i386/_structs.h"
struct __darwin_i386_thread_state {
   unsigned int __eax ;
   unsigned int __ebx ;
   unsigned int __ecx ;
   unsigned int __edx ;
   unsigned int __edi ;
   unsigned int __esi ;
   unsigned int __ebp ;
   unsigned int __esp ;
   unsigned int __ss ;
   unsigned int __eflags ;
   unsigned int __eip ;
   unsigned int __cs ;
   unsigned int __ds ;
   unsigned int __es ;
   unsigned int __fs ;
   unsigned int __gs ;
};
#line 89 "/usr/include/mach/i386/_structs.h"
struct __darwin_fp_control {
   unsigned short __invalid : 1 ;
   unsigned short __denorm : 1 ;
   unsigned short __zdiv : 1 ;
   unsigned short __ovrfl : 1 ;
   unsigned short __undfl : 1 ;
   unsigned short __precis : 1 ;
   unsigned short  : 2 ;
   unsigned short __pc : 2 ;
   unsigned short __rc : 2 ;
   unsigned short  : 1 ;
   unsigned short  : 3 ;
};
#line 114 "/usr/include/mach/i386/_structs.h"
typedef struct __darwin_fp_control __darwin_fp_control_t;
#line 147 "/usr/include/mach/i386/_structs.h"
struct __darwin_fp_status {
   unsigned short __invalid : 1 ;
   unsigned short __denorm : 1 ;
   unsigned short __zdiv : 1 ;
   unsigned short __ovrfl : 1 ;
   unsigned short __undfl : 1 ;
   unsigned short __precis : 1 ;
   unsigned short __stkflt : 1 ;
   unsigned short __errsumm : 1 ;
   unsigned short __c0 : 1 ;
   unsigned short __c1 : 1 ;
   unsigned short __c2 : 1 ;
   unsigned short __tos : 3 ;
   unsigned short __c3 : 1 ;
   unsigned short __busy : 1 ;
};
#line 164 "/usr/include/mach/i386/_structs.h"
typedef struct __darwin_fp_status __darwin_fp_status_t;
#line 191 "/usr/include/mach/i386/_structs.h"
struct __darwin_mmst_reg {
   char __mmst_reg[10] ;
   char __mmst_rsrv[6] ;
};
#line 210 "/usr/include/mach/i386/_structs.h"
struct __darwin_xmm_reg {
   char __xmm_reg[16] ;
};
#line 232 "/usr/include/mach/i386/_structs.h"
struct __darwin_i386_float_state {
   int __fpu_reserved[2] ;
   struct __darwin_fp_control __fpu_fcw ;
   struct __darwin_fp_status __fpu_fsw ;
   __uint8_t __fpu_ftw ;
   __uint8_t __fpu_rsrv1 ;
   __uint16_t __fpu_fop ;
   __uint32_t __fpu_ip ;
   __uint16_t __fpu_cs ;
   __uint16_t __fpu_rsrv2 ;
   __uint32_t __fpu_dp ;
   __uint16_t __fpu_ds ;
   __uint16_t __fpu_rsrv3 ;
   __uint32_t __fpu_mxcsr ;
   __uint32_t __fpu_mxcsrmask ;
   struct __darwin_mmst_reg __fpu_stmm0 ;
   struct __darwin_mmst_reg __fpu_stmm1 ;
   struct __darwin_mmst_reg __fpu_stmm2 ;
   struct __darwin_mmst_reg __fpu_stmm3 ;
   struct __darwin_mmst_reg __fpu_stmm4 ;
   struct __darwin_mmst_reg __fpu_stmm5 ;
   struct __darwin_mmst_reg __fpu_stmm6 ;
   struct __darwin_mmst_reg __fpu_stmm7 ;
   struct __darwin_xmm_reg __fpu_xmm0 ;
   struct __darwin_xmm_reg __fpu_xmm1 ;
   struct __darwin_xmm_reg __fpu_xmm2 ;
   struct __darwin_xmm_reg __fpu_xmm3 ;
   struct __darwin_xmm_reg __fpu_xmm4 ;
   struct __darwin_xmm_reg __fpu_xmm5 ;
   struct __darwin_xmm_reg __fpu_xmm6 ;
   struct __darwin_xmm_reg __fpu_xmm7 ;
   char __fpu_rsrv4[224] ;
   int __fpu_reserved1 ;
};
#line 269 "/usr/include/mach/i386/_structs.h"
struct __darwin_i386_avx_state {
   int __fpu_reserved[2] ;
   struct __darwin_fp_control __fpu_fcw ;
   struct __darwin_fp_status __fpu_fsw ;
   __uint8_t __fpu_ftw ;
   __uint8_t __fpu_rsrv1 ;
   __uint16_t __fpu_fop ;
   __uint32_t __fpu_ip ;
   __uint16_t __fpu_cs ;
   __uint16_t __fpu_rsrv2 ;
   __uint32_t __fpu_dp ;
   __uint16_t __fpu_ds ;
   __uint16_t __fpu_rsrv3 ;
   __uint32_t __fpu_mxcsr ;
   __uint32_t __fpu_mxcsrmask ;
   struct __darwin_mmst_reg __fpu_stmm0 ;
   struct __darwin_mmst_reg __fpu_stmm1 ;
   struct __darwin_mmst_reg __fpu_stmm2 ;
   struct __darwin_mmst_reg __fpu_stmm3 ;
   struct __darwin_mmst_reg __fpu_stmm4 ;
   struct __darwin_mmst_reg __fpu_stmm5 ;
   struct __darwin_mmst_reg __fpu_stmm6 ;
   struct __darwin_mmst_reg __fpu_stmm7 ;
   struct __darwin_xmm_reg __fpu_xmm0 ;
   struct __darwin_xmm_reg __fpu_xmm1 ;
   struct __darwin_xmm_reg __fpu_xmm2 ;
   struct __darwin_xmm_reg __fpu_xmm3 ;
   struct __darwin_xmm_reg __fpu_xmm4 ;
   struct __darwin_xmm_reg __fpu_xmm5 ;
   struct __darwin_xmm_reg __fpu_xmm6 ;
   struct __darwin_xmm_reg __fpu_xmm7 ;
   char __fpu_rsrv4[224] ;
   int __fpu_reserved1 ;
   char __avx_reserved1[64] ;
   struct __darwin_xmm_reg __fpu_ymmh0 ;
   struct __darwin_xmm_reg __fpu_ymmh1 ;
   struct __darwin_xmm_reg __fpu_ymmh2 ;
   struct __darwin_xmm_reg __fpu_ymmh3 ;
   struct __darwin_xmm_reg __fpu_ymmh4 ;
   struct __darwin_xmm_reg __fpu_ymmh5 ;
   struct __darwin_xmm_reg __fpu_ymmh6 ;
   struct __darwin_xmm_reg __fpu_ymmh7 ;
};
#line 402 "/usr/include/mach/i386/_structs.h"
struct __darwin_i386_exception_state {
   __uint16_t __trapno ;
   __uint16_t __cpu ;
   __uint32_t __err ;
   __uint32_t __faultvaddr ;
};
#line 422 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_debug_state32 {
   unsigned int __dr0 ;
   unsigned int __dr1 ;
   unsigned int __dr2 ;
   unsigned int __dr3 ;
   unsigned int __dr4 ;
   unsigned int __dr5 ;
   unsigned int __dr6 ;
   unsigned int __dr7 ;
};
#line 454 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_thread_state64 {
   __uint64_t __rax ;
   __uint64_t __rbx ;
   __uint64_t __rcx ;
   __uint64_t __rdx ;
   __uint64_t __rdi ;
   __uint64_t __rsi ;
   __uint64_t __rbp ;
   __uint64_t __rsp ;
   __uint64_t __r8 ;
   __uint64_t __r9 ;
   __uint64_t __r10 ;
   __uint64_t __r11 ;
   __uint64_t __r12 ;
   __uint64_t __r13 ;
   __uint64_t __r14 ;
   __uint64_t __r15 ;
   __uint64_t __rip ;
   __uint64_t __rflags ;
   __uint64_t __cs ;
   __uint64_t __fs ;
   __uint64_t __gs ;
};
#line 509 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_float_state64 {
   int __fpu_reserved[2] ;
   struct __darwin_fp_control __fpu_fcw ;
   struct __darwin_fp_status __fpu_fsw ;
   __uint8_t __fpu_ftw ;
   __uint8_t __fpu_rsrv1 ;
   __uint16_t __fpu_fop ;
   __uint32_t __fpu_ip ;
   __uint16_t __fpu_cs ;
   __uint16_t __fpu_rsrv2 ;
   __uint32_t __fpu_dp ;
   __uint16_t __fpu_ds ;
   __uint16_t __fpu_rsrv3 ;
   __uint32_t __fpu_mxcsr ;
   __uint32_t __fpu_mxcsrmask ;
   struct __darwin_mmst_reg __fpu_stmm0 ;
   struct __darwin_mmst_reg __fpu_stmm1 ;
   struct __darwin_mmst_reg __fpu_stmm2 ;
   struct __darwin_mmst_reg __fpu_stmm3 ;
   struct __darwin_mmst_reg __fpu_stmm4 ;
   struct __darwin_mmst_reg __fpu_stmm5 ;
   struct __darwin_mmst_reg __fpu_stmm6 ;
   struct __darwin_mmst_reg __fpu_stmm7 ;
   struct __darwin_xmm_reg __fpu_xmm0 ;
   struct __darwin_xmm_reg __fpu_xmm1 ;
   struct __darwin_xmm_reg __fpu_xmm2 ;
   struct __darwin_xmm_reg __fpu_xmm3 ;
   struct __darwin_xmm_reg __fpu_xmm4 ;
   struct __darwin_xmm_reg __fpu_xmm5 ;
   struct __darwin_xmm_reg __fpu_xmm6 ;
   struct __darwin_xmm_reg __fpu_xmm7 ;
   struct __darwin_xmm_reg __fpu_xmm8 ;
   struct __darwin_xmm_reg __fpu_xmm9 ;
   struct __darwin_xmm_reg __fpu_xmm10 ;
   struct __darwin_xmm_reg __fpu_xmm11 ;
   struct __darwin_xmm_reg __fpu_xmm12 ;
   struct __darwin_xmm_reg __fpu_xmm13 ;
   struct __darwin_xmm_reg __fpu_xmm14 ;
   struct __darwin_xmm_reg __fpu_xmm15 ;
   char __fpu_rsrv4[96] ;
   int __fpu_reserved1 ;
};
#line 560 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_avx_state64 {
   int __fpu_reserved[2] ;
   struct __darwin_fp_control __fpu_fcw ;
   struct __darwin_fp_status __fpu_fsw ;
   __uint8_t __fpu_ftw ;
   __uint8_t __fpu_rsrv1 ;
   __uint16_t __fpu_fop ;
   __uint32_t __fpu_ip ;
   __uint16_t __fpu_cs ;
   __uint16_t __fpu_rsrv2 ;
   __uint32_t __fpu_dp ;
   __uint16_t __fpu_ds ;
   __uint16_t __fpu_rsrv3 ;
   __uint32_t __fpu_mxcsr ;
   __uint32_t __fpu_mxcsrmask ;
   struct __darwin_mmst_reg __fpu_stmm0 ;
   struct __darwin_mmst_reg __fpu_stmm1 ;
   struct __darwin_mmst_reg __fpu_stmm2 ;
   struct __darwin_mmst_reg __fpu_stmm3 ;
   struct __darwin_mmst_reg __fpu_stmm4 ;
   struct __darwin_mmst_reg __fpu_stmm5 ;
   struct __darwin_mmst_reg __fpu_stmm6 ;
   struct __darwin_mmst_reg __fpu_stmm7 ;
   struct __darwin_xmm_reg __fpu_xmm0 ;
   struct __darwin_xmm_reg __fpu_xmm1 ;
   struct __darwin_xmm_reg __fpu_xmm2 ;
   struct __darwin_xmm_reg __fpu_xmm3 ;
   struct __darwin_xmm_reg __fpu_xmm4 ;
   struct __darwin_xmm_reg __fpu_xmm5 ;
   struct __darwin_xmm_reg __fpu_xmm6 ;
   struct __darwin_xmm_reg __fpu_xmm7 ;
   struct __darwin_xmm_reg __fpu_xmm8 ;
   struct __darwin_xmm_reg __fpu_xmm9 ;
   struct __darwin_xmm_reg __fpu_xmm10 ;
   struct __darwin_xmm_reg __fpu_xmm11 ;
   struct __darwin_xmm_reg __fpu_xmm12 ;
   struct __darwin_xmm_reg __fpu_xmm13 ;
   struct __darwin_xmm_reg __fpu_xmm14 ;
   struct __darwin_xmm_reg __fpu_xmm15 ;
   char __fpu_rsrv4[96] ;
   int __fpu_reserved1 ;
   char __avx_reserved1[64] ;
   struct __darwin_xmm_reg __fpu_ymmh0 ;
   struct __darwin_xmm_reg __fpu_ymmh1 ;
   struct __darwin_xmm_reg __fpu_ymmh2 ;
   struct __darwin_xmm_reg __fpu_ymmh3 ;
   struct __darwin_xmm_reg __fpu_ymmh4 ;
   struct __darwin_xmm_reg __fpu_ymmh5 ;
   struct __darwin_xmm_reg __fpu_ymmh6 ;
   struct __darwin_xmm_reg __fpu_ymmh7 ;
   struct __darwin_xmm_reg __fpu_ymmh8 ;
   struct __darwin_xmm_reg __fpu_ymmh9 ;
   struct __darwin_xmm_reg __fpu_ymmh10 ;
   struct __darwin_xmm_reg __fpu_ymmh11 ;
   struct __darwin_xmm_reg __fpu_ymmh12 ;
   struct __darwin_xmm_reg __fpu_ymmh13 ;
   struct __darwin_xmm_reg __fpu_ymmh14 ;
   struct __darwin_xmm_reg __fpu_ymmh15 ;
};
#line 751 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_exception_state64 {
   __uint16_t __trapno ;
   __uint16_t __cpu ;
   __uint32_t __err ;
   __uint64_t __faultvaddr ;
};
#line 771 "/usr/include/mach/i386/_structs.h"
struct __darwin_x86_debug_state64 {
   __uint64_t __dr0 ;
   __uint64_t __dr1 ;
   __uint64_t __dr2 ;
   __uint64_t __dr3 ;
   __uint64_t __dr4 ;
   __uint64_t __dr5 ;
   __uint64_t __dr6 ;
   __uint64_t __dr7 ;
};
#line 38 "/usr/include/i386/_mcontext.h"
struct __darwin_mcontext32 {
   struct __darwin_i386_exception_state __es ;
   struct __darwin_i386_thread_state __ss ;
   struct __darwin_i386_float_state __fs ;
};
#line 46 "/usr/include/i386/_mcontext.h"
struct __darwin_mcontext_avx32 {
   struct __darwin_i386_exception_state __es ;
   struct __darwin_i386_thread_state __ss ;
   struct __darwin_i386_avx_state __fs ;
};
#line 76 "/usr/include/i386/_mcontext.h"
struct __darwin_mcontext64 {
   struct __darwin_x86_exception_state64 __es ;
   struct __darwin_x86_thread_state64 __ss ;
   struct __darwin_x86_float_state64 __fs ;
};
#line 84 "/usr/include/i386/_mcontext.h"
struct __darwin_mcontext_avx64 {
   struct __darwin_x86_exception_state64 __es ;
   struct __darwin_x86_thread_state64 __ss ;
   struct __darwin_x86_avx_state64 __fs ;
};
#line 115 "/usr/include/i386/_mcontext.h"
typedef struct __darwin_mcontext64 *mcontext_t;
#line 30 "/usr/include/sys/_pthread/_pthread_attr_t.h"
typedef __darwin_pthread_attr_t pthread_attr_t;
#line 36 "/usr/include/sys/_types/_sigaltstack.h"
struct __darwin_sigaltstack {
   void *ss_sp ;
   __darwin_size_t ss_size ;
   int ss_flags ;
};
#line 42 "/usr/include/sys/_types/_sigaltstack.h"
typedef struct __darwin_sigaltstack stack_t;
#line 34 "/usr/include/sys/_types/_ucontext.h"
struct __darwin_ucontext {
   int uc_onstack ;
   __darwin_sigset_t uc_sigmask ;
   struct __darwin_sigaltstack uc_stack ;
   struct __darwin_ucontext *uc_link ;
   __darwin_size_t uc_mcsize ;
   struct __darwin_mcontext64 *uc_mcontext ;
};
#line 48 "/usr/include/sys/_types/_ucontext.h"
typedef struct __darwin_ucontext ucontext_t;
#line 30 "/usr/include/sys/_types/_sigset_t.h"
typedef __darwin_sigset_t sigset_t;
#line 30 "/usr/include/sys/_types/_uid_t.h"
typedef __darwin_uid_t uid_t;
#line 158 "/usr/include/sys/signal.h"
union sigval {
   int sival_int ;
   void *sival_ptr ;
};
#line 168 "/usr/include/sys/signal.h"
struct sigevent {
   int sigev_notify ;
   int sigev_signo ;
   union sigval sigev_value ;
   void (*sigev_notify_function)(union sigval  ) ;
   pthread_attr_t *sigev_notify_attributes ;
};
#line 177 "/usr/include/sys/signal.h"
struct __siginfo {
   int si_signo ;
   int si_errno ;
   int si_code ;
   pid_t si_pid ;
   uid_t si_uid ;
   int si_status ;
   void *si_addr ;
   union sigval si_value ;
   long si_band ;
   unsigned long __pad[7] ;
};
#line 177 "/usr/include/sys/signal.h"
typedef struct __siginfo siginfo_t;
#line 269 "/usr/include/sys/signal.h"
union __sigaction_u {
   void (*__sa_handler)(int  ) ;
   void (*__sa_sigaction)(int  , struct __siginfo * , void * ) ;
};
#line 276 "/usr/include/sys/signal.h"
struct __sigaction {
   union __sigaction_u __sigaction_u ;
   void (*sa_tramp)(void * , int  , int  , siginfo_t * , void * ) ;
   sigset_t sa_mask ;
   int sa_flags ;
};
#line 286 "/usr/include/sys/signal.h"
struct sigaction {
   union __sigaction_u __sigaction_u ;
   sigset_t sa_mask ;
   int sa_flags ;
};
#line 331 "/usr/include/sys/signal.h"
typedef void (*sig_t)(int  );
#line 348 "/usr/include/sys/signal.h"
struct sigvec {
   void (*sv_handler)(int  ) ;
   int sv_mask ;
   int sv_flags ;
};
#line 367 "/usr/include/sys/signal.h"
struct sigstack {
   char *ss_sp ;
   int ss_onstack ;
};
#line 30 "/usr/include/sys/_types/_int8_t.h"
typedef signed char int8_t;
#line 30 "/usr/include/sys/_types/_int16_t.h"
typedef short int16_t;
#line 30 "/usr/include/sys/_types/_int32_t.h"
typedef int int32_t;
#line 30 "/usr/include/sys/_types/_int64_t.h"
typedef long long int64_t;
#line 31 "/usr/include/_types/_uint8_t.h"
typedef unsigned char uint8_t;
#line 31 "/usr/include/_types/_uint16_t.h"
typedef unsigned short uint16_t;
#line 31 "/usr/include/_types/_uint32_t.h"
typedef unsigned int uint32_t;
#line 31 "/usr/include/_types/_uint64_t.h"
typedef unsigned long long uint64_t;
#line 38 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int8_t int_least8_t;
#line 39 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int16_t int_least16_t;
#line 40 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int32_t int_least32_t;
#line 41 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int64_t int_least64_t;
#line 42 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint8_t uint_least8_t;
#line 43 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint16_t uint_least16_t;
#line 44 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint32_t uint_least32_t;
#line 45 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint64_t uint_least64_t;
#line 49 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int8_t int_fast8_t;
#line 50 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int16_t int_fast16_t;
#line 51 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int32_t int_fast32_t;
#line 52 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef int64_t int_fast64_t;
#line 53 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint8_t uint_fast8_t;
#line 54 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint16_t uint_fast16_t;
#line 55 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint32_t uint_fast32_t;
#line 56 "/usr/local/lib/gcc/x86_64-apple-darwin15.6.0/6.3.0/include-fixed/stdint.h"
typedef uint64_t uint_fast64_t;
#line 30 "/usr/include/sys/_types/_intptr_t.h"
typedef __darwin_intptr_t intptr_t;
#line 30 "/usr/include/sys/_types/_uintptr_t.h"
typedef unsigned long uintptr_t;
#line 32 "/usr/include/_types/_intmax_t.h"
typedef long intmax_t;
#line 32 "/usr/include/_types/_uintmax_t.h"
typedef unsigned long uintmax_t;
#line 30 "/usr/include/sys/_types/_timeval.h"
struct timeval {
   __darwin_time_t tv_sec ;
   __darwin_suseconds_t tv_usec ;
};
#line 89 "/usr/include/sys/resource.h"
typedef __uint64_t rlim_t;
#line 152 "/usr/include/sys/resource.h"
struct rusage {
   struct timeval ru_utime ;
   struct timeval ru_stime ;
   long ru_maxrss ;
   long ru_ixrss ;
   long ru_idrss ;
   long ru_isrss ;
   long ru_minflt ;
   long ru_majflt ;
   long ru_nswap ;
   long ru_inblock ;
   long ru_oublock ;
   long ru_msgsnd ;
   long ru_msgrcv ;
   long ru_nsignals ;
   long ru_nvcsw ;
   long ru_nivcsw ;
};
#line 192 "/usr/include/sys/resource.h"
typedef void *rusage_info_t;
#line 194 "/usr/include/sys/resource.h"
struct rusage_info_v0 {
   uint8_t ri_uuid[16] ;
   uint64_t ri_user_time ;
   uint64_t ri_system_time ;
   uint64_t ri_pkg_idle_wkups ;
   uint64_t ri_interrupt_wkups ;
   uint64_t ri_pageins ;
   uint64_t ri_wired_size ;
   uint64_t ri_resident_size ;
   uint64_t ri_phys_footprint ;
   uint64_t ri_proc_start_abstime ;
   uint64_t ri_proc_exit_abstime ;
};
#line 208 "/usr/include/sys/resource.h"
struct rusage_info_v1 {
   uint8_t ri_uuid[16] ;
   uint64_t ri_user_time ;
   uint64_t ri_system_time ;
   uint64_t ri_pkg_idle_wkups ;
   uint64_t ri_interrupt_wkups ;
   uint64_t ri_pageins ;
   uint64_t ri_wired_size ;
   uint64_t ri_resident_size ;
   uint64_t ri_phys_footprint ;
   uint64_t ri_proc_start_abstime ;
   uint64_t ri_proc_exit_abstime ;
   uint64_t ri_child_user_time ;
   uint64_t ri_child_system_time ;
   uint64_t ri_child_pkg_idle_wkups ;
   uint64_t ri_child_interrupt_wkups ;
   uint64_t ri_child_pageins ;
   uint64_t ri_child_elapsed_abstime ;
};
#line 228 "/usr/include/sys/resource.h"
struct rusage_info_v2 {
   uint8_t ri_uuid[16] ;
   uint64_t ri_user_time ;
   uint64_t ri_system_time ;
   uint64_t ri_pkg_idle_wkups ;
   uint64_t ri_interrupt_wkups ;
   uint64_t ri_pageins ;
   uint64_t ri_wired_size ;
   uint64_t ri_resident_size ;
   uint64_t ri_phys_footprint ;
   uint64_t ri_proc_start_abstime ;
   uint64_t ri_proc_exit_abstime ;
   uint64_t ri_child_user_time ;
   uint64_t ri_child_system_time ;
   uint64_t ri_child_pkg_idle_wkups ;
   uint64_t ri_child_interrupt_wkups ;
   uint64_t ri_child_pageins ;
   uint64_t ri_child_elapsed_abstime ;
   uint64_t ri_diskio_bytesread ;
   uint64_t ri_diskio_byteswritten ;
};
#line 250 "/usr/include/sys/resource.h"
struct rusage_info_v3 {
   uint8_t ri_uuid[16] ;
   uint64_t ri_user_time ;
   uint64_t ri_system_time ;
   uint64_t ri_pkg_idle_wkups ;
   uint64_t ri_interrupt_wkups ;
   uint64_t ri_pageins ;
   uint64_t ri_wired_size ;
   uint64_t ri_resident_size ;
   uint64_t ri_phys_footprint ;
   uint64_t ri_proc_start_abstime ;
   uint64_t ri_proc_exit_abstime ;
   uint64_t ri_child_user_time ;
   uint64_t ri_child_system_time ;
   uint64_t ri_child_pkg_idle_wkups ;
   uint64_t ri_child_interrupt_wkups ;
   uint64_t ri_child_pageins ;
   uint64_t ri_child_elapsed_abstime ;
   uint64_t ri_diskio_bytesread ;
   uint64_t ri_diskio_byteswritten ;
   uint64_t ri_cpu_time_qos_default ;
   uint64_t ri_cpu_time_qos_maintenance ;
   uint64_t ri_cpu_time_qos_background ;
   uint64_t ri_cpu_time_qos_utility ;
   uint64_t ri_cpu_time_qos_legacy ;
   uint64_t ri_cpu_time_qos_user_initiated ;
   uint64_t ri_cpu_time_qos_user_interactive ;
   uint64_t ri_billed_system_time ;
   uint64_t ri_serviced_system_time ;
};
#line 281 "/usr/include/sys/resource.h"
typedef struct rusage_info_v3 rusage_info_current;
#line 325 "/usr/include/sys/resource.h"
struct rlimit {
   rlim_t rlim_cur ;
   rlim_t rlim_max ;
};
#line 353 "/usr/include/sys/resource.h"
struct proc_rlimit_control_wakeupmon {
   uint32_t wm_flags ;
   int32_t wm_rate ;
};
#line 194 "/usr/include/sys/wait.h"
struct __anonstruct_w_T_3 {
   unsigned int w_Termsig : 7 ;
   unsigned int w_Coredump : 1 ;
   unsigned int w_Retcode : 8 ;
   unsigned int w_Filler : 16 ;
};
#line 194 "/usr/include/sys/wait.h"
struct __anonstruct_w_S_4 {
   unsigned int w_Stopval : 8 ;
   unsigned int w_Stopsig : 8 ;
   unsigned int w_Filler : 16 ;
};
#line 194 "/usr/include/sys/wait.h"
union wait {
   int w_status ;
   struct __anonstruct_w_T_3 w_T ;
   struct __anonstruct_w_S_4 w_S ;
};
#line 31 "/usr/include/sys/_types/_ct_rune_t.h"
typedef __darwin_ct_rune_t ct_rune_t;
#line 30 "/usr/include/sys/_types/_rune_t.h"
typedef __darwin_rune_t rune_t;
#line 33 "/usr/include/sys/_types/_wchar_t.h"
typedef __darwin_wchar_t wchar_t;
#line 82 "/usr/include/stdlib.h"
struct __anonstruct_div_t_5 {
   int quot ;
   int rem ;
};
#line 82 "/usr/include/stdlib.h"
typedef struct __anonstruct_div_t_5 div_t;
#line 87 "/usr/include/stdlib.h"
struct __anonstruct_ldiv_t_6 {
   long quot ;
   long rem ;
};
#line 87 "/usr/include/stdlib.h"
typedef struct __anonstruct_ldiv_t_6 ldiv_t;
#line 93 "/usr/include/stdlib.h"
struct __anonstruct_lldiv_t_7 {
   long long quot ;
   long long rem ;
};
#line 93 "/usr/include/stdlib.h"
typedef struct __anonstruct_lldiv_t_7 lldiv_t;
#line 81 "/usr/include/i386/types.h"
typedef unsigned char u_int8_t;
#line 82 "/usr/include/i386/types.h"
typedef unsigned short u_int16_t;
#line 83 "/usr/include/i386/types.h"
typedef unsigned int u_int32_t;
#line 84 "/usr/include/i386/types.h"
typedef unsigned long long u_int64_t;
#line 87 "/usr/include/i386/types.h"
typedef int64_t register_t;
#line 97 "/usr/include/i386/types.h"
typedef u_int64_t user_addr_t;
#line 98 "/usr/include/i386/types.h"
typedef u_int64_t user_size_t;
#line 99 "/usr/include/i386/types.h"
typedef int64_t user_ssize_t;
#line 100 "/usr/include/i386/types.h"
typedef int64_t user_long_t;
#line 101 "/usr/include/i386/types.h"
typedef u_int64_t user_ulong_t;
#line 102 "/usr/include/i386/types.h"
typedef int64_t user_time_t;
#line 103 "/usr/include/i386/types.h"
typedef int64_t user_off_t;
#line 111 "/usr/include/i386/types.h"
typedef u_int64_t syscall_arg_t;
#line 30 "/usr/include/sys/_types/_dev_t.h"
typedef __darwin_dev_t dev_t;
#line 30 "/usr/include/sys/_types/_mode_t.h"
typedef __darwin_mode_t mode_t;
#line 132 "/usr/include/sys/unistd.h"
struct accessx_descriptor {
   unsigned int ad_name_offset ;
   int ad_flags ;
   int ad_pad[2] ;
};
#line 30 "/usr/include/sys/_types/_gid_t.h"
typedef __darwin_gid_t gid_t;
#line 30 "/usr/include/sys/_types/_useconds_t.h"
typedef __darwin_useconds_t useconds_t;
#line 46 "/usr/include/sys/_types/_fd_def.h"
struct fd_set {
   __int32_t fds_bits[1024UL / (sizeof(__int32_t ) * 8UL)] ;
};
#line 46 "/usr/include/sys/_types/_fd_def.h"
typedef struct fd_set fd_set;
#line 30 "/usr/include/sys/_types/_timespec.h"
struct timespec {
   __darwin_time_t tv_sec ;
   long tv_nsec ;
};
#line 30 "/usr/include/sys/_types/_time_t.h"
typedef __darwin_time_t time_t;
#line 30 "/usr/include/sys/_types/_suseconds_t.h"
typedef __darwin_suseconds_t suseconds_t;
#line 30 "/usr/include/sys/_types/_uuid_t.h"
typedef __darwin_uuid_t uuid_t;
#line 736 "/usr/include/unistd.h"
struct fssearchblock;
#line 736
struct fssearchblock;
#line 737
struct searchstate;
#line 737
struct searchstate;
#line 331 "/usr/include/sys/fcntl.h"
struct flock {
   off_t l_start ;
   off_t l_len ;
   pid_t l_pid ;
   short l_type ;
   short l_whence ;
};
#line 346 "/usr/include/sys/fcntl.h"
struct flocktimeout {
   struct flock fl ;
   struct timespec timeout ;
};
#line 359 "/usr/include/sys/fcntl.h"
struct radvisory {
   off_t ra_offset ;
   int ra_count ;
};
#line 366 "/usr/include/sys/fcntl.h"
struct fcodeblobs {
   void *f_cd_hash ;
   size_t f_hash_size ;
   void *f_cd_buffer ;
   size_t f_cd_size ;
   unsigned int *f_out_size ;
   int f_arch ;
   int __padding ;
};
#line 366 "/usr/include/sys/fcntl.h"
typedef struct fcodeblobs fcodeblobs_t;
#line 383 "/usr/include/sys/fcntl.h"
struct fsignatures {
   off_t fs_file_start ;
   void *fs_blob_start ;
   size_t fs_blob_size ;
};
#line 383 "/usr/include/sys/fcntl.h"
typedef struct fsignatures fsignatures_t;
#line 397 "/usr/include/sys/fcntl.h"
struct fstore {
   unsigned int fst_flags ;
   int fst_posmode ;
   off_t fst_offset ;
   off_t fst_length ;
   off_t fst_bytesalloc ;
};
#line 397 "/usr/include/sys/fcntl.h"
typedef struct fstore fstore_t;
#line 407 "/usr/include/sys/fcntl.h"
struct fbootstraptransfer {
   off_t fbt_offset ;
   size_t fbt_length ;
   void *fbt_buffer ;
};
#line 407 "/usr/include/sys/fcntl.h"
typedef struct fbootstraptransfer fbootstraptransfer_t;
#line 435
#pragma pack(4)
#line 437 "/usr/include/sys/fcntl.h"
struct log2phys {
   unsigned int l2p_flags ;
   off_t l2p_contigbytes ;
   off_t l2p_devoffset ;
};
#line 447
#pragma pack()
#line 30 "/usr/include/sys/_types/_filesec_t.h"
struct _filesec;
#line 30
struct _filesec;
#line 31 "/usr/include/sys/_types/_filesec_t.h"
typedef struct _filesec *filesec_t;
#line 460 "/usr/include/sys/fcntl.h"
enum __anonenum_filesec_property_t_8 {
    FILESEC_OWNER = 1,
    FILESEC_GROUP = 2,
    FILESEC_UUID = 3,
    FILESEC_MODE = 4,
    FILESEC_ACL = 5,
    FILESEC_GRPUUID = 6,
    FILESEC_ACL_RAW = 100,
    FILESEC_ACL_ALLOCSIZE = 101
} ;
#line 460 "/usr/include/sys/fcntl.h"
typedef enum __anonenum_filesec_property_t_8 filesec_property_t;
#line 84 "/usr/include/sys/types.h"
typedef unsigned char u_char;
#line 85 "/usr/include/sys/types.h"
typedef unsigned short u_short;
#line 86 "/usr/include/sys/types.h"
typedef unsigned int u_int;
#line 88 "/usr/include/sys/types.h"
typedef unsigned long u_long;
#line 91 "/usr/include/sys/types.h"
typedef unsigned short ushort;
#line 92 "/usr/include/sys/types.h"
typedef unsigned int uint;
#line 95 "/usr/include/sys/types.h"
typedef u_int64_t u_quad_t;
#line 96 "/usr/include/sys/types.h"
typedef int64_t quad_t;
#line 97 "/usr/include/sys/types.h"
typedef quad_t *qaddr_t;
#line 99 "/usr/include/sys/types.h"
typedef char *caddr_t;
#line 100 "/usr/include/sys/types.h"
typedef int32_t daddr_t;
#line 104 "/usr/include/sys/types.h"
typedef u_int32_t fixpt_t;
#line 30 "/usr/include/sys/_types/_blkcnt_t.h"
typedef __darwin_blkcnt_t blkcnt_t;
#line 30 "/usr/include/sys/_types/_blksize_t.h"
typedef __darwin_blksize_t blksize_t;
#line 30 "/usr/include/sys/_types/_in_addr_t.h"
typedef __uint32_t in_addr_t;
#line 30 "/usr/include/sys/_types/_in_port_t.h"
typedef __uint16_t in_port_t;
#line 30 "/usr/include/sys/_types/_ino_t.h"
typedef __darwin_ino_t ino_t;
#line 30 "/usr/include/sys/_types/_ino64_t.h"
typedef __darwin_ino64_t ino64_t;
#line 30 "/usr/include/sys/_types/_key_t.h"
typedef __int32_t key_t;
#line 30 "/usr/include/sys/_types/_nlink_t.h"
typedef __uint16_t nlink_t;
#line 124 "/usr/include/sys/types.h"
typedef int32_t segsz_t;
#line 125 "/usr/include/sys/types.h"
typedef int32_t swblk_t;
#line 30 "/usr/include/sys/_types/_clock_t.h"
typedef __darwin_clock_t clock_t;
#line 30 "/usr/include/sys/_types/_rsize_t.h"
typedef __darwin_size_t rsize_t;
#line 30 "/usr/include/sys/_types/_errno_t.h"
typedef int errno_t;
#line 185 "/usr/include/sys/types.h"
typedef __int32_t fd_mask;
#line 30 "/usr/include/sys/_pthread/_pthread_cond_t.h"
typedef __darwin_pthread_cond_t pthread_cond_t;
#line 30 "/usr/include/sys/_pthread/_pthread_condattr_t.h"
typedef __darwin_pthread_condattr_t pthread_condattr_t;
#line 30 "/usr/include/sys/_pthread/_pthread_mutex_t.h"
typedef __darwin_pthread_mutex_t pthread_mutex_t;
#line 30 "/usr/include/sys/_pthread/_pthread_mutexattr_t.h"
typedef __darwin_pthread_mutexattr_t pthread_mutexattr_t;
#line 30 "/usr/include/sys/_pthread/_pthread_once_t.h"
typedef __darwin_pthread_once_t pthread_once_t;
#line 30 "/usr/include/sys/_pthread/_pthread_rwlock_t.h"
typedef __darwin_pthread_rwlock_t pthread_rwlock_t;
#line 30 "/usr/include/sys/_pthread/_pthread_rwlockattr_t.h"
typedef __darwin_pthread_rwlockattr_t pthread_rwlockattr_t;
#line 30 "/usr/include/sys/_pthread/_pthread_t.h"
typedef __darwin_pthread_t pthread_t;
#line 30 "/usr/include/sys/_pthread/_pthread_key_t.h"
typedef __darwin_pthread_key_t pthread_key_t;
#line 30 "/usr/include/sys/_types/_fsblkcnt_t.h"
typedef __darwin_fsblkcnt_t fsblkcnt_t;
#line 30 "/usr/include/sys/_types/_fsfilcnt_t.h"
typedef __darwin_fsfilcnt_t fsfilcnt_t;
#line 110 "/usr/include/sys/stat.h"
struct ostat {
   __uint16_t st_dev ;
   ino_t st_ino ;
   mode_t st_mode ;
   nlink_t st_nlink ;
   __uint16_t st_uid ;
   __uint16_t st_gid ;
   __uint16_t st_rdev ;
   __int32_t st_size ;
   struct timespec st_atimespec ;
   struct timespec st_mtimespec ;
   struct timespec st_ctimespec ;
   __int32_t st_blksize ;
   __int32_t st_blocks ;
   __uint32_t st_flags ;
   __uint32_t st_gen ;
};
#line 182 "/usr/include/sys/stat.h"
struct stat {
   dev_t st_dev ;
   mode_t st_mode ;
   nlink_t st_nlink ;
   __darwin_ino64_t st_ino ;
   uid_t st_uid ;
   gid_t st_gid ;
   dev_t st_rdev ;
   struct timespec st_atimespec ;
   struct timespec st_mtimespec ;
   struct timespec st_ctimespec ;
   struct timespec st_birthtimespec ;
   off_t st_size ;
   blkcnt_t st_blocks ;
   blksize_t st_blksize ;
   __uint32_t st_flags ;
   __uint32_t st_gen ;
   __int32_t st_lspare ;
   __int64_t st_qspare[2] ;
};
#line 221 "/usr/include/sys/stat.h"
struct stat64 {
   dev_t st_dev ;
   mode_t st_mode ;
   nlink_t st_nlink ;
   __darwin_ino64_t st_ino ;
   uid_t st_uid ;
   gid_t st_gid ;
   dev_t st_rdev ;
   struct timespec st_atimespec ;
   struct timespec st_mtimespec ;
   struct timespec st_ctimespec ;
   struct timespec st_birthtimespec ;
   off_t st_size ;
   blkcnt_t st_blocks ;
   blksize_t st_blksize ;
   __uint32_t st_flags ;
   __uint32_t st_gen ;
   __int32_t st_lspare ;
   __int64_t st_qspare[2] ;
};
#line 7 "test.c"
struct Copter {
   float gps ;
   int x ;
   int y ;
};
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
#line 39 "/usr/include/sys/stdio.h"
extern int renameat(int  , char const   * , int  , char const   * ) ;
#line 156 "/usr/include/stdio.h"
extern FILE *__stdinp ;
#line 157
extern FILE *__stdoutp ;
#line 158
extern FILE *__stderrp ;
#line 231
extern void clearerr(FILE * ) ;
#line 232
extern int fclose(FILE * ) ;
#line 233
extern int feof(FILE * ) ;
#line 234
extern int ferror(FILE * ) ;
#line 235
extern int fflush(FILE * ) ;
#line 236
extern int fgetc(FILE * ) ;
#line 237
extern int fgetpos(FILE * __restrict   , fpos_t * ) ;
#line 238
extern char *fgets(char * __restrict   , int  , FILE * ) ;
#line 242
extern FILE *fopen(char const   * __restrict   , char const   * __restrict   )  __asm__("_fopen")  ;
#line 244
extern int ( /* format attribute */  fprintf)(FILE * __restrict   , char const   * __restrict   
                                              , ...) ;
#line 245
extern int fputc(int  , FILE * ) ;
#line 246
extern int fputs(char const   * __restrict   , FILE * __restrict   )  __asm__("_fputs")  ;
#line 247
extern size_t fread(void * __restrict   , size_t  , size_t  , FILE * __restrict   ) ;
#line 248
extern FILE *freopen(char const   * __restrict   , char const   * __restrict   , FILE * __restrict   )  __asm__("_freopen")  ;
#line 250
extern int ( /* format attribute */  fscanf)(FILE * __restrict   , char const   * __restrict   
                                             , ...) ;
#line 251
extern int fseek(FILE * , long  , int  ) ;
#line 252
extern int fsetpos(FILE * , fpos_t const   * ) ;
#line 253
extern long ftell(FILE * ) ;
#line 254
extern size_t fwrite(void const   * __restrict   , size_t  , size_t  , FILE * __restrict   )  __asm__("_fwrite")  ;
#line 255
extern int getc(FILE * ) ;
#line 256
extern int getchar(void) ;
#line 257
extern char *gets(char * ) ;
#line 258
extern void perror(char const   * ) ;
#line 259
extern int ( /* format attribute */  printf)(char const   * __restrict    , ...) ;
#line 260
extern int putc(int  , FILE * ) ;
#line 261
extern int putchar(int  ) ;
#line 262
extern int puts(char const   * ) ;
#line 263
extern int remove(char const   * ) ;
#line 264
extern int rename(char const   * , char const   * ) ;
#line 265
extern void rewind(FILE * ) ;
#line 266
extern int ( /* format attribute */  scanf)(char const   * __restrict    , ...) ;
#line 267
extern void setbuf(FILE * __restrict   , char * __restrict   ) ;
#line 268
extern int setvbuf(FILE * __restrict   , char * __restrict   , int  , size_t  ) ;
#line 269
extern int ( /* format attribute */  sprintf)(char * __restrict   , char const   * __restrict   
                                              , ...) ;
#line 270
extern int ( /* format attribute */  sscanf)(char const   * __restrict   , char const   * __restrict   
                                             , ...) ;
#line 271
extern FILE *tmpfile(void) ;
#line 274
extern char __attribute__((__deprecated__("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tmpnam(3), it is highly recommended that you use mkstemp(3) instead.")))  *tmpnam(char * ) ;
#line 277
extern int ungetc(int  , FILE * ) ;
#line 278
extern int ( /* format attribute */  vfprintf)(FILE * __restrict   , char const   * __restrict   ,
                                               va_list  ) ;
#line 279
extern int ( /* format attribute */  vprintf)(char const   * __restrict   , va_list  ) ;
#line 280
extern int ( /* format attribute */  vsprintf)(char * __restrict   , char const   * __restrict   ,
                                               va_list  ) ;
#line 296
extern char *ctermid(char * ) ;
#line 302
extern FILE *fdopen(int  , char const   * )  __asm__("_fdopen")  ;
#line 304
extern int fileno(FILE * ) ;
#line 315
extern int pclose(FILE * ) ;
#line 319
extern FILE *popen(char const   * , char const   * )  __asm__("_popen")  ;
#line 337
extern int __srget(FILE * ) ;
#line 338
extern int ( /* format attribute */  __svfscanf)(FILE * , char const   * , va_list  ) ;
#line 339
extern int __swbuf(int  , FILE * ) ;
#line 348 "/usr/include/stdio.h"
__inline extern int __attribute__((__gnu_inline__))  ( __attribute__((__always_inline__)) __sputc)(int _c ,
                                                                                                   FILE *_p ) 
{ 
  unsigned char *tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;

  {
#line 349
  (_p->_w) --;
#line 349
  if (_p->_w >= 0) {
#line 350
    tmp = _p->_p;
#line 350
    (_p->_p) ++;
#line 350
    tmp___0 = (unsigned char )_c;
#line 350
    *tmp = tmp___0;
#line 350
    return ((int __attribute__((__gnu_inline__))  )tmp___0);
  } else
#line 349
  if (_p->_w >= _p->_lbfsize) {
#line 349
    if ((int )((char )_c) != 10) {
#line 350
      tmp = _p->_p;
#line 350
      (_p->_p) ++;
#line 350
      tmp___0 = (unsigned char )_c;
#line 350
      *tmp = tmp___0;
#line 350
      return ((int __attribute__((__gnu_inline__))  )tmp___0);
    } else {
#line 352
      tmp___1 = __swbuf(_c, _p);
#line 352
      return ((int __attribute__((__gnu_inline__))  )tmp___1);
    }
  } else {
#line 352
    tmp___1 = __swbuf(_c, _p);
#line 352
    return ((int __attribute__((__gnu_inline__))  )tmp___1);
  }
}
}
#line 374
extern void flockfile(FILE * ) ;
#line 375
extern int ftrylockfile(FILE * ) ;
#line 376
extern void funlockfile(FILE * ) ;
#line 377
extern int getc_unlocked(FILE * ) ;
#line 378
extern int getchar_unlocked(void) ;
#line 379
extern int putc_unlocked(int  , FILE * ) ;
#line 380
extern int putchar_unlocked(int  ) ;
#line 384
extern int getw(FILE * ) ;
#line 385
extern int putw(int  , FILE * ) ;
#line 389
extern char __attribute__((__deprecated__("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead.")))  *tempnam(char const   * ,
                                                                                                                                                                                                                                             char const   * )  __asm__("_tempnam")  ;
#line 414
extern int fseeko(FILE * , off_t  , int  ) ;
#line 415
extern off_t ftello(FILE * ) ;
#line 421
extern int ( /* format attribute */  snprintf)(char * __restrict   , size_t  , char const   * __restrict   
                                               , ...) ;
#line 422
extern int ( /* format attribute */  vfscanf)(FILE * __restrict   , char const   * __restrict   ,
                                              va_list  ) ;
#line 423
extern int ( /* format attribute */  vscanf)(char const   * __restrict   , va_list  ) ;
#line 424
extern int ( /* format attribute */  vsnprintf)(char * __restrict   , size_t  , char const   * __restrict   ,
                                                va_list  ) ;
#line 425
extern int ( /* format attribute */  vsscanf)(char const   * __restrict   , char const   * __restrict   ,
                                              va_list  ) ;
#line 439
extern int ( /* format attribute */  dprintf)(int  , char const   * __restrict   
                                              , ...) ;
#line 440
extern int ( /* format attribute */  vdprintf)(int  , char const   * __restrict   ,
                                               va_list  ) ;
#line 441
extern ssize_t getdelim(char ** __restrict   , size_t * __restrict   , int  , FILE * __restrict   ) ;
#line 442
extern ssize_t getline(char ** __restrict   , size_t * __restrict   , FILE * __restrict   ) ;
#line 452
extern int const   sys_nerr ;
#line 453
extern char const   * const  sys_errlist[] ;
#line 455
extern int ( /* format attribute */  asprintf)(char ** __restrict   , char const   * __restrict   
                                               , ...) ;
#line 456
extern char *ctermid_r(char * ) ;
#line 457
extern char *fgetln(FILE * , size_t * ) ;
#line 458
extern char const   *fmtcheck(char const   * , char const   * ) ;
#line 459
extern int fpurge(FILE * ) ;
#line 460
extern void setbuffer(FILE * , char * , int  ) ;
#line 461
extern int setlinebuf(FILE * ) ;
#line 462
extern int ( /* format attribute */  vasprintf)(char ** __restrict   , char const   * __restrict   ,
                                                va_list  ) ;
#line 463
extern FILE *zopen(char const   * , char const   * , int  ) ;
#line 469
extern FILE *funopen(void const   * , int (*)(void * , char * , int  ) , int (*)(void * ,
                                                                                 char const   * ,
                                                                                 int  ) ,
                     fpos_t (*)(void * , fpos_t  , int  ) , int (*)(void * ) ) ;
#line 42 "/usr/include/secure/_stdio.h"
extern int __sprintf_chk(char * __restrict   , int  , size_t  , char const   * __restrict   
                         , ...) ;
#line 52
extern int __snprintf_chk(char * __restrict   , size_t  , int  , size_t  , char const   * __restrict   
                          , ...) ;
#line 61
extern int __vsprintf_chk(char * __restrict   , int  , size_t  , char const   * __restrict   ,
                          va_list  ) ;
#line 70
extern int __vsnprintf_chk(char * __restrict   , size_t  , int  , size_t  , char const   * __restrict   ,
                           va_list  ) ;
#line 390 "/usr/include/sys/signal.h"
extern void (*signal(int  , void (*)(int  ) ))(int  ) ;
#line 383 "/usr/include/sys/resource.h"
extern int getpriority(int  , id_t  ) ;
#line 385
extern int getiopolicy_np(int  , int  ) ;
#line 387
extern int getrlimit(int  , struct rlimit * )  __asm__("_getrlimit")  ;
#line 388
extern int getrusage(int  , struct rusage * ) ;
#line 389
extern int setpriority(int  , id_t  , int  ) ;
#line 391
extern int setiopolicy_np(int  , int  , int  ) ;
#line 393
extern int setrlimit(int  , struct rlimit  const  * )  __asm__("_setrlimit")  ;
#line 44 "/usr/include/libkern/i386/_OSByteOrder.h"
__inline static __uint16_t _OSSwapInt16(__uint16_t _data ) 
{ 


  {
#line 50
  return ((__uint16_t )(((int )_data << 8) | ((int )_data >> 8)));
}
}
#line 53 "/usr/include/libkern/i386/_OSByteOrder.h"
__inline static __uint32_t _OSSwapInt32(__uint32_t _data ) 
{ 


  {
#line 62
  __asm__  ("bswap   %0": "+r" (_data));
#line 63
  return (_data);
}
}
#line 91 "/usr/include/libkern/i386/_OSByteOrder.h"
__inline static __uint64_t _OSSwapInt64(__uint64_t _data ) 
{ 


  {
#line 97
  __asm__  ("bswap   %0": "+r" (_data));
#line 98
  return (_data);
}
}
#line 248 "/usr/include/sys/wait.h"
extern pid_t wait(int * )  __asm__("_wait")  ;
#line 249
extern pid_t waitpid(pid_t  , int * , int  )  __asm__("_waitpid")  ;
#line 251
extern int waitid(idtype_t  , id_t  , siginfo_t * , int  )  __asm__("_waitid")  ;
#line 254
extern pid_t wait3(int * , int  , struct rusage * ) ;
#line 255
extern pid_t wait4(pid_t  , int * , int  , struct rusage * ) ;
#line 32 "/usr/include/alloca.h"
extern void *alloca(size_t  ) ;
#line 117 "/usr/include/stdlib.h"
extern int __mb_cur_max ;
#line 128
extern  __attribute__((__noreturn__)) void abort(void) ;
#line 129
extern int abs(int  )  __attribute__((__const__)) ;
#line 130
extern int atexit(void (*)(void) ) ;
#line 131
extern double atof(char const   * ) ;
#line 132
extern int atoi(char const   * ) ;
#line 133
extern long atol(char const   * ) ;
#line 135
extern long long atoll(char const   * ) ;
#line 138
extern void *bsearch(void const   * , void const   * , size_t  , size_t  , int (*)(void const   * ,
                                                                                   void const   * ) ) ;
#line 140
extern void *calloc(size_t  , size_t  ) ;
#line 141
extern div_t div(int  , int  )  __attribute__((__const__)) ;
#line 142
extern  __attribute__((__noreturn__)) void exit(int  ) ;
#line 143
extern void free(void * ) ;
#line 144
extern char *getenv(char const   * ) ;
#line 145
extern long labs(long  )  __attribute__((__const__)) ;
#line 146
extern ldiv_t ldiv(long  , long  )  __attribute__((__const__)) ;
#line 148
extern long long llabs(long long  ) ;
#line 150
extern lldiv_t lldiv(long long  , long long  ) ;
#line 152
extern void *malloc(size_t  ) ;
#line 153
extern int mblen(char const   * , size_t  ) ;
#line 154
extern size_t mbstowcs(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 155
extern int mbtowc(wchar_t * __restrict   , char const   * __restrict   , size_t  ) ;
#line 156
extern int posix_memalign(void ** , size_t  , size_t  ) ;
#line 157
extern void qsort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 159
extern int rand(void) ;
#line 160
extern void *realloc(void * , size_t  ) ;
#line 161
extern void srand(unsigned int  ) ;
#line 162
extern double strtod(char const   * , char ** )  __asm__("_strtod")  ;
#line 163
extern float strtof(char const   * , char ** )  __asm__("_strtof")  ;
#line 164
extern long strtol(char const   * , char ** , int  ) ;
#line 165
extern long double strtold(char const   * , char ** ) ;
#line 168
extern long long strtoll(char const   * , char ** , int  ) ;
#line 171
extern unsigned long strtoul(char const   * , char ** , int  ) ;
#line 174
extern unsigned long long strtoull(char const   * , char ** , int  ) ;
#line 177
extern int system(char const   * )  __asm__("_system")  ;
#line 178
extern size_t wcstombs(char * __restrict   , wchar_t const   * __restrict   , size_t  ) ;
#line 179
extern int wctomb(char * , wchar_t  ) ;
#line 182
extern  __attribute__((__noreturn__)) void _Exit(int  ) ;
#line 183
extern long a64l(char const   * ) ;
#line 184
extern double drand48(void) ;
#line 185
extern char *ecvt(double  , int  , int * __restrict   , int * __restrict   ) ;
#line 186
extern double erand48(unsigned short * ) ;
#line 187
extern char *fcvt(double  , int  , int * __restrict   , int * __restrict   ) ;
#line 188
extern char *gcvt(double  , int  , char * ) ;
#line 189
extern int getsubopt(char ** , char * const  * , char ** ) ;
#line 190
extern int grantpt(int  ) ;
#line 192
extern char *initstate(unsigned int  , char * , size_t  ) ;
#line 196
extern long jrand48(unsigned short * ) ;
#line 197
extern char *l64a(long  ) ;
#line 198
extern void lcong48(unsigned short * ) ;
#line 199
extern long lrand48(void) ;
#line 200
extern char *mktemp(char * ) ;
#line 201
extern int mkstemp(char * ) ;
#line 202
extern long mrand48(void) ;
#line 203
extern long nrand48(unsigned short * ) ;
#line 204
extern int posix_openpt(int  ) ;
#line 205
extern char *ptsname(int  ) ;
#line 206
extern int putenv(char * )  __asm__("_putenv")  ;
#line 207
extern long random(void) ;
#line 208
extern int rand_r(unsigned int * ) ;
#line 210
extern char *realpath(char const   * __restrict   , char * __restrict   )  __asm__("_realpath$DARWIN_EXTSN")  ;
#line 214
extern unsigned short *seed48(unsigned short * ) ;
#line 216
extern int setenv(char const   * , char const   * , int  )  __asm__("_setenv")  ;
#line 218
extern void setkey(char const   * )  __asm__("_setkey")  ;
#line 222
extern char *setstate(char const   * ) ;
#line 223
extern void srand48(long  ) ;
#line 225
extern void srandom(unsigned int  ) ;
#line 229
extern int unlockpt(int  ) ;
#line 231
extern int unsetenv(char const   * )  __asm__("_unsetenv")  ;
#line 243
extern u_int32_t arc4random(void) ;
#line 244
extern void arc4random_addrandom(unsigned char * , int  ) ;
#line 245
extern void arc4random_buf(void * , size_t  ) ;
#line 246
extern void arc4random_stir(void) ;
#line 247
extern u_int32_t arc4random_uniform(u_int32_t  ) ;
#line 256
extern char *cgetcap(char * , char const   * , int  ) ;
#line 257
extern int cgetclose(void) ;
#line 258
extern int cgetent(char ** , char ** , char const   * ) ;
#line 259
extern int cgetfirst(char ** , char ** ) ;
#line 260
extern int cgetmatch(char const   * , char const   * ) ;
#line 261
extern int cgetnext(char ** , char ** ) ;
#line 262
extern int cgetnum(char * , char const   * , long * ) ;
#line 263
extern int cgetset(char const   * ) ;
#line 264
extern int cgetstr(char * , char const   * , char ** ) ;
#line 265
extern int cgetustr(char * , char const   * , char ** ) ;
#line 267
extern int daemon(int  , int  )  __asm__("_daemon$1050") __attribute__((__deprecated__)) ;
#line 268
extern char *devname(dev_t  , mode_t  ) ;
#line 269
extern char *devname_r(dev_t  , mode_t  , char *buf , int len ) ;
#line 270
extern char *getbsize(int * , long * ) ;
#line 271
extern int getloadavg(double * , int  ) ;
#line 272
extern char const   *getprogname(void) ;
#line 275
extern int heapsort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 281
extern int mergesort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 287
extern void psort(void * , size_t  , size_t  , int (*)(void const   * , void const   * ) ) ;
#line 293
extern void psort_r(void * , size_t  , size_t  , void * , int (*)(void * , void const   * ,
                                                                  void const   * ) ) ;
#line 299
extern void qsort_r(void * , size_t  , size_t  , void * , int (*)(void * , void const   * ,
                                                                  void const   * ) ) ;
#line 301
extern int radixsort(unsigned char const   ** , int  , unsigned char const   * , unsigned int  ) ;
#line 303
extern void setprogname(char const   * ) ;
#line 304
extern int sradixsort(unsigned char const   ** , int  , unsigned char const   * ,
                      unsigned int  ) ;
#line 306
extern void sranddev(void) ;
#line 307
extern void srandomdev(void) ;
#line 308
extern void *reallocf(void * , size_t  ) ;
#line 310
extern long long strtoq(char const   * , char ** , int  ) ;
#line 312
extern unsigned long long strtouq(char const   * , char ** , int  ) ;
#line 315
extern char *suboptarg ;
#line 316
extern void *valloc(size_t  ) ;
#line 185 "/usr/include/sys/unistd.h"
extern int getattrlistbulk(int  , void * , void * , size_t  , uint64_t  ) ;
#line 203
extern int faccessat(int  , char const   * , int  , int  ) ;
#line 204
extern int fchownat(int  , char const   * , uid_t  , gid_t  , int  ) ;
#line 205
extern int linkat(int  , char const   * , int  , char const   * , int  ) ;
#line 206
extern ssize_t readlinkat(int  , char const   * , char * , size_t  ) ;
#line 207
extern int symlinkat(char const   * , int  , char const   * ) ;
#line 208
extern int unlinkat(int  , char const   * , int  ) ;
#line 209
extern int getattrlistat(int  , char const   * , void * , void * , size_t  , unsigned long  ) ;
#line 429 "/usr/include/unistd.h"
extern  __attribute__((__noreturn__)) void _exit(int  ) ;
#line 430
extern int access(char const   * , int  ) ;
#line 431
extern unsigned int alarm(unsigned int  ) ;
#line 433
extern int chdir(char const   * ) ;
#line 434
extern int chown(char const   * , uid_t  , gid_t  ) ;
#line 436
extern int close(int  )  __asm__("_close")  ;
#line 438
extern int dup(int  ) ;
#line 439
extern int dup2(int  , int  ) ;
#line 440
extern int execl(char const   * , char const   *  , ...) ;
#line 441
extern int execle(char const   * , char const   *  , ...) ;
#line 442
extern int execlp(char const   * , char const   *  , ...) ;
#line 443
extern int execv(char const   * , char * const  * ) ;
#line 444
extern int execve(char const   * , char * const  * , char * const  * ) ;
#line 445
extern int execvp(char const   * , char * const  * ) ;
#line 446
extern pid_t fork(void) ;
#line 447
extern long fpathconf(int  , int  ) ;
#line 448
extern char *getcwd(char * , size_t  ) ;
#line 449
extern gid_t getegid(void) ;
#line 450
extern uid_t geteuid(void) ;
#line 451
extern gid_t getgid(void) ;
#line 455
extern int getgroups(int  , gid_t * ) ;
#line 457
extern char *getlogin(void) ;
#line 458
extern pid_t getpgrp(void) ;
#line 459
extern pid_t getpid(void) ;
#line 460
extern pid_t getppid(void) ;
#line 461
extern uid_t getuid(void) ;
#line 462
extern int isatty(int  ) ;
#line 463
extern int link(char const   * , char const   * ) ;
#line 464
extern off_t lseek(int  , off_t  , int  ) ;
#line 465
extern long pathconf(char const   * , int  ) ;
#line 467
extern int pause(void)  __asm__("_pause")  ;
#line 469
extern int pipe(int * ) ;
#line 471
extern ssize_t read(int  , void * , size_t  )  __asm__("_read")  ;
#line 473
extern int rmdir(char const   * ) ;
#line 474
extern int setgid(gid_t  ) ;
#line 475
extern int setpgid(pid_t  , pid_t  ) ;
#line 476
extern pid_t setsid(void) ;
#line 477
extern int setuid(uid_t  ) ;
#line 479
extern unsigned int sleep(unsigned int  )  __asm__("_sleep")  ;
#line 482
extern long sysconf(int  ) ;
#line 483
extern pid_t tcgetpgrp(int  ) ;
#line 484
extern int tcsetpgrp(int  , pid_t  ) ;
#line 485
extern char *ttyname(int  ) ;
#line 488
extern int ttyname_r(int  , char * , size_t  )  __asm__("_ttyname_r")  ;
#line 493
extern int unlink(char const   * ) ;
#line 495
extern ssize_t write(int  , void const   * , size_t  )  __asm__("_write")  ;
#line 506
extern size_t confstr(int  , char * , size_t  )  __asm__("_confstr")  ;
#line 508
extern int getopt(int  , char * const  * , char const   * )  __asm__("_getopt")  ;
#line 510
extern char *optarg ;
#line 511
extern int optind ;
#line 511
extern int opterr ;
#line 511
extern int optopt ;
#line 536
extern void __attribute__((__deprecated__))  *brk(void const   * ) ;
#line 539
extern int chroot(char const   * ) ;
#line 542
extern char *crypt(char const   * , char const   * ) ;
#line 549
extern void encrypt(char * , int  )  __asm__("_encrypt")  ;
#line 553
extern int fchdir(int  ) ;
#line 554
extern long gethostid(void) ;
#line 555
extern pid_t getpgid(pid_t  ) ;
#line 556
extern pid_t getsid(pid_t  ) ;
#line 560
extern int getdtablesize(void) ;
#line 561
extern int getpagesize(void)  __attribute__((__const__)) ;
#line 562
extern char *getpass(char const   * ) ;
#line 567
extern char *getwd(char * ) ;
#line 570
extern int lchown(char const   * , uid_t  , gid_t  )  __asm__("_lchown")  ;
#line 572
extern int lockf(int  , int  , off_t  )  __asm__("_lockf")  ;
#line 574
extern int nice(int  )  __asm__("_nice")  ;
#line 576
extern ssize_t pread(int  , void * , size_t  , off_t  )  __asm__("_pread")  ;
#line 578
extern ssize_t pwrite(int  , void const   * , size_t  , off_t  )  __asm__("_pwrite")  ;
#line 585
extern void __attribute__((__deprecated__))  *sbrk(int  ) ;
#line 591
extern pid_t setpgrp(void)  __asm__("_setpgrp")  ;
#line 596
extern int setregid(gid_t  , gid_t  )  __asm__("_setregid")  ;
#line 598
extern int setreuid(uid_t  , uid_t  )  __asm__("_setreuid")  ;
#line 600
extern void swab(void const   * __restrict   , void * __restrict   , ssize_t  ) ;
#line 601
extern void sync(void) ;
#line 602
extern int truncate(char const   * , off_t  ) ;
#line 603
extern useconds_t ualarm(useconds_t  , useconds_t  ) ;
#line 604
extern int usleep(useconds_t  )  __asm__("_usleep")  ;
#line 605
extern pid_t vfork(void) ;
#line 608
extern int fsync(int  )  __asm__("_fsync")  ;
#line 610
extern int ftruncate(int  , off_t  ) ;
#line 611
extern int getlogin_r(char * , size_t  ) ;
#line 624
extern int fchown(int  , uid_t  , gid_t  ) ;
#line 625
extern int gethostname(char * , size_t  ) ;
#line 626
extern ssize_t readlink(char const   * __restrict   , char * __restrict   , size_t  ) ;
#line 627
extern int setegid(gid_t  ) ;
#line 628
extern int seteuid(uid_t  ) ;
#line 629
extern int symlink(char const   * , char const   * ) ;
#line 52 "/usr/include/sys/_types/_fd_def.h"
__inline static int __darwin_fd_isset(int _n , struct fd_set  const  *_p ) 
{ 


  {
#line 55
  return (_p->fds_bits[(unsigned long )_n / (sizeof(__int32_t ) * 8UL)] & (1 << (unsigned long )_n % (sizeof(__int32_t ) * 8UL)));
}
}
#line 114 "/usr/include/sys/select.h"
extern int pselect(int  , fd_set * __restrict   , fd_set * __restrict   , fd_set * __restrict   ,
                   struct timespec  const  * __restrict   , sigset_t const   * __restrict   )  __asm__("_pselect$1050")  ;
#line 39 "/usr/include/sys/_select.h"
extern int select(int  , fd_set * __restrict   , fd_set * __restrict   , fd_set * __restrict   ,
                  struct timeval * __restrict   )  __asm__("_select$1050")  ;
#line 646 "/usr/include/unistd.h"
extern int accessx_np(struct accessx_descriptor  const  * , size_t  , int * , uid_t  ) ;
#line 647
extern int acct(char const   * ) ;
#line 648
extern int add_profil(char * , size_t  , unsigned long  , unsigned int  ) ;
#line 649
extern void endusershell(void) ;
#line 650
extern int execvP(char const   * , char const   * , char * const  * ) ;
#line 651
extern char *fflagstostr(unsigned long  ) ;
#line 652
extern int getdomainname(char * , int  ) ;
#line 653
extern int getgrouplist(char const   * , int  , int * , int * ) ;
#line 39 "/usr/include/gethostuuid.h"
extern int gethostuuid(unsigned char * , struct timespec  const  * ) ;
#line 663 "/usr/include/unistd.h"
extern mode_t getmode(void const   * , mode_t  ) ;
#line 664
extern int getpeereid(int  , uid_t * , gid_t * ) ;
#line 665
extern int getsgroups_np(int * , unsigned char * ) ;
#line 666
extern char *getusershell(void) ;
#line 667
extern int getwgroups_np(int * , unsigned char * ) ;
#line 668
extern int initgroups(char const   * , int  ) ;
#line 669
extern int iruserok(unsigned long  , int  , char const   * , char const   * ) ;
#line 670
extern int iruserok_sa(void const   * , int  , int  , char const   * , char const   * ) ;
#line 671
extern int issetugid(void) ;
#line 672
extern char *mkdtemp(char * ) ;
#line 673
extern int mknod(char const   * , mode_t  , dev_t  ) ;
#line 674
extern int mkpath_np(char const   *path , mode_t omode ) ;
#line 676
extern int mkstemps(char * , int  ) ;
#line 678
extern int nfssvc(int  , void * ) ;
#line 679
extern int profil(char * , size_t  , unsigned long  , unsigned int  ) ;
#line 680
extern int pthread_setugid_np(uid_t  , gid_t  ) ;
#line 681
extern int pthread_getugid_np(uid_t * , gid_t * ) ;
#line 682
extern int rcmd(char ** , int  , char const   * , char const   * , char const   * ,
                int * ) ;
#line 683
extern int rcmd_af(char ** , int  , char const   * , char const   * , char const   * ,
                   int * , int  ) ;
#line 685
extern int reboot(int  ) ;
#line 686
extern int revoke(char const   * ) ;
#line 687
extern int rresvport(int * ) ;
#line 688
extern int rresvport_af(int * , int  ) ;
#line 689
extern int ruserok(char const   * , int  , char const   * , char const   * ) ;
#line 690
extern int setdomainname(char const   * , int  ) ;
#line 691
extern int setgroups(int  , gid_t const   * ) ;
#line 692
extern void sethostid(long  ) ;
#line 693
extern int sethostname(char const   * , int  ) ;
#line 699
extern int setlogin(char const   * ) ;
#line 700
extern void *setmode(char const   * )  __asm__("_setmode")  ;
#line 701
extern int setrgid(gid_t  ) ;
#line 702
extern int setruid(uid_t  ) ;
#line 703
extern int setsgroups_np(int  , unsigned char * const   ) ;
#line 704
extern void setusershell(void) ;
#line 705
extern int setwgroups_np(int  , unsigned char * const   ) ;
#line 706
extern int strtofflags(char ** , unsigned long * , unsigned long * ) ;
#line 707
extern int swapon(char const   * ) ;
#line 708
extern int syscall(int   , ...) ;
#line 709
extern int ttyslot(void) ;
#line 710
extern int undelete(char const   * ) ;
#line 711
extern int unwhiteout(char const   * ) ;
#line 719
extern int fgetattrlist(int  , void * , void * , size_t  , unsigned int  ) ;
#line 720
extern int fsetattrlist(int  , void * , void * , size_t  , unsigned int  ) ;
#line 721
extern int getattrlist(char const   * , void * , void * , size_t  , unsigned int  )  __asm__("_getattrlist")  ;
#line 722
extern int setattrlist(char const   * , void * , void * , size_t  , unsigned int  )  __asm__("_setattrlist")  ;
#line 723
extern int exchangedata(char const   * , char const   * , unsigned int  ) ;
#line 724
extern int getdirentriesattr(int  , void * , void * , size_t  , unsigned int * , unsigned int * ,
                             unsigned int * , unsigned int  ) ;
#line 739
extern int searchfs(char const   * , struct fssearchblock * , unsigned long * , unsigned int  ,
                    unsigned int  , struct searchstate * ) ;
#line 740
extern int fsctl(char const   * , unsigned long  , void * , unsigned int  ) ;
#line 741
extern int ffsctl(int  , unsigned long  , void * , unsigned int  ) ;
#line 746
extern int fsync_volume_np(int  , int  ) ;
#line 747
extern int sync_volume_np(char const   * , int  ) ;
#line 749
extern int optreset ;
#line 478 "/usr/include/sys/fcntl.h"
extern int open(char const   * , int   , ...)  __asm__("_open")  ;
#line 480
extern int openat(int  , char const   * , int   , ...)  __asm__("_openat")  ;
#line 482
extern int creat(char const   * , mode_t  )  __asm__("_creat")  ;
#line 483
extern int fcntl(int  , int   , ...)  __asm__("_fcntl")  ;
#line 486
extern int openx_np(char const   * , int  , filesec_t  ) ;
#line 491
extern int open_dprotected_np(char const   * , int  , int  , int   , ...) ;
#line 492
extern int flock(int  , int  ) ;
#line 493
extern filesec_t filesec_init(void) ;
#line 494
extern filesec_t filesec_dup(filesec_t  ) ;
#line 495
extern void filesec_free(filesec_t  ) ;
#line 496
extern int filesec_get_property(filesec_t  , filesec_property_t  , void * ) ;
#line 497
extern int filesec_query_property(filesec_t  , filesec_property_t  , int * ) ;
#line 498
extern int filesec_set_property(filesec_t  , filesec_property_t  , void const   * ) ;
#line 499
extern int filesec_unset_property(filesec_t  , filesec_property_t  ) ;
#line 352 "/usr/include/sys/stat.h"
extern int chmod(char const   * , mode_t  )  __asm__("_chmod")  ;
#line 353
extern int fchmod(int  , mode_t  )  __asm__("_fchmod")  ;
#line 354
extern int fstat(int  , struct stat * )  __asm__("_fstat$INODE64")  ;
#line 355
extern int lstat(char const   * , struct stat * )  __asm__("_lstat$INODE64")  ;
#line 356
extern int mkdir(char const   * , mode_t  ) ;
#line 357
extern int mkfifo(char const   * , mode_t  ) ;
#line 358
extern int stat(char const   * , struct stat * )  __asm__("_stat$INODE64")  ;
#line 360
extern mode_t umask(mode_t  ) ;
#line 363
extern int fchmodat(int  , char const   * , mode_t  , int  ) ;
#line 364
extern int fstatat(int  , char const   * , struct stat * , int  )  __asm__("_fstatat$INODE64")  ;
#line 365
extern int mkdirat(int  , char const   * , mode_t  ) ;
#line 372
extern int chflags(char const   * , __uint32_t  ) ;
#line 373
extern int chmodx_np(char const   * , filesec_t  ) ;
#line 374
extern int fchflags(int  , __uint32_t  ) ;
#line 375
extern int fchmodx_np(int  , filesec_t  ) ;
#line 376
extern int fstatx_np(int  , struct stat * , filesec_t  )  __asm__("_fstatx_np$INODE64")  ;
#line 377
extern int lchflags(char const   * , __uint32_t  ) ;
#line 378
extern int lchmod(char const   * , mode_t  ) ;
#line 379
extern int lstatx_np(char const   * , struct stat * , filesec_t  )  __asm__("_lstatx_np$INODE64")  ;
#line 380
extern int mkdirx_np(char const   * , filesec_t  ) ;
#line 381
extern int mkfifox_np(char const   * , filesec_t  ) ;
#line 382
extern int statx_np(char const   * , struct stat * , filesec_t  )  __asm__("_statx_np$INODE64")  ;
#line 383
extern int umaskx_np(filesec_t  )  __attribute__((__deprecated__)) ;
#line 387
extern int fstatx64_np(int  , struct stat64 * , filesec_t  )  __attribute__((__deprecated__)) ;
#line 388
extern int lstatx64_np(char const   * , struct stat64 * , filesec_t  )  __attribute__((__deprecated__)) ;
#line 389
extern int statx64_np(char const   * , struct stat64 * , filesec_t  )  __attribute__((__deprecated__)) ;
#line 390
extern int fstat64(int  , struct stat64 * )  __attribute__((__deprecated__)) ;
#line 391
extern int lstat64(char const   * , struct stat64 * )  __attribute__((__deprecated__)) ;
#line 392
extern int stat64(char const   * , struct stat64 * )  __attribute__((__deprecated__)) ;
void __deserialize_scalarFloat32(float *ptr , int fd ) ;
void __serialize_Copter(struct Copter *ptr , int fd ) ;
void __deserialize_Copter(struct Copter *ptr , int fd ) ;
void __deserialize_scalarInt32(int *ptr , int fd ) ;
void __serialize_scalarFloat32(float *ptr , int fd ) ;
void __serialize_scalarInt32(int *ptr , int fd ) ;
void __deserialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __serialize_scalarFloat32(& ptr->gps, fd);
  __serialize_scalarInt32(& ptr->x, fd);
  __serialize_scalarInt32(& ptr->y, fd);
}
}
void __deserialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __deserialize_scalarFloat32(& ptr->gps, fd);
  __deserialize_scalarInt32(& ptr->x, fd);
  __deserialize_scalarInt32(& ptr->y, fd);
}
}
void __deserialize_scalarInt32(int *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize_scalarInt32(int *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
#line 13 "test.c"
int main(void) 
{ 
  int x ;
  struct Copter myCopter ;
  int fd3 ;
  int fd4 ;

  {
#line 16
  myCopter.gps = (float )2.5;
#line 17
  myCopter.x = 1;
#line 18
  myCopter.y = 2;
  {
  SERIALIZE: ;
  {
  fd3 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __serialize_Copter(& myCopter, fd3);
  close(fd3);
  }
  }
  {
  DESERIALIZE: ;
  {
  fd4 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __deserialize_Copter(& myCopter, fd4);
  close(fd4);
  }
  }
#line 26
  return (0);
}
}
