/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

void *_memoize[4096] ;
int _memoizeMax ;
void malloc ;
int read(int fd , void *buf , int count ) ;
int write(int fd , void *buf , int count ) ;
int close(int fd ) ;
void open ;
#line 1 "wes.i"
typedef char bool;
#line 2 "wes.i"
typedef unsigned char __uint8_t;
#line 3 "wes.i"
typedef short __int16_t;
#line 4 "wes.i"
typedef unsigned short __uint16_t;
#line 5 "wes.i"
typedef int __int32_t;
#line 6 "wes.i"
typedef unsigned int __uint32_t;
#line 7 "wes.i"
typedef long long __int64_t;
#line 8 "wes.i"
typedef unsigned long long __uint64_t;
#line 9 "wes.i"
typedef signed char int8_t;
#line 10 "wes.i"
typedef short int16_t;
#line 11 "wes.i"
typedef int int32_t;
#line 12 "wes.i"
typedef long long int64_t;
#line 13 "wes.i"
typedef unsigned char uint8_t;
#line 14 "wes.i"
typedef unsigned short uint16_t;
#line 15 "wes.i"
typedef unsigned int uint32_t;
#line 16 "wes.i"
typedef unsigned long long uint64_t;
#line 18
enum LandStateType {
    LandStateType_FlyToLocation = 0,
    LandStateType_Descending = 1
} ;
#line 22 "wes.i"
typedef enum LandStateType LandStateType;
#line 24
enum control_mode_t {
    STABILIZE = 0,
    ACRO = 1,
    ALT_HOLD = 2,
    AUTO = 3,
    GUIDED = 4,
    LOITER = 5,
    RTL = 6,
    CIRCLE = 7,
    LAND = 9,
    DRIFT = 11,
    SPORT = 13,
    FLIP = 14,
    AUTOTUNE = 15,
    POSHOLD = 16,
    BRAKE = 17,
    THROW = 18,
    AVOID_ADSB = 19,
    GUIDED_NOGPS = 20,
    SMART_RTL = 21
} ;
#line 46 "wes.i"
typedef enum control_mode_t control_mode_t;
#line 48
enum mode_reason_t {
    MODE_REASON_UNKNOWN = 0,
    MODE_REASON_TX_COMMAND = 1,
    MODE_REASON_GCS_COMMAND = 2,
    MODE_REASON_RADIO_FAILSAFE = 3,
    MODE_REASON_BATTERY_FAILSAFE = 4,
    MODE_REASON_GCS_FAILSAFE = 5,
    MODE_REASON_EKF_FAILSAFE = 6,
    MODE_REASON_GPS_GLITCH = 7,
    MODE_REASON_MISSION_END = 8,
    MODE_REASON_THROTTLE_LAND_ESCAPE = 9,
    MODE_REASON_FENCE_BREACH = 10,
    MODE_REASON_TERRAIN_FAILSAFE = 11,
    MODE_REASON_BRAKE_TIMEOUT = 12,
    MODE_REASON_FLIP_COMPLETE = 13,
    MODE_REASON_AVOIDANCE = 14,
    MODE_REASON_AVOIDANCE_RECOVERY = 15,
    MODE_REASON_THROW_COMPLETE = 16,
    MODE_REASON_TERMINATE = 17
} ;
#line 68 "wes.i"
typedef enum mode_reason_t mode_reason_t;
#line 70
enum PayloadPlaceStateType {
    PayloadPlaceStateType_FlyToLocation = 0,
    PayloadPlaceStateType_Calibrating_Hover_Start = 1,
    PayloadPlaceStateType_Calibrating_Hover = 2,
    PayloadPlaceStateType_Descending_Start = 3,
    PayloadPlaceStateType_Descending = 4,
    PayloadPlaceStateType_Releasing_Start = 5,
    PayloadPlaceStateType_Releasing = 6,
    PayloadPlaceStateType_Released = 7,
    PayloadPlaceStateType_Ascending_Start = 8,
    PayloadPlaceStateType_Ascending = 9,
    PayloadPlaceStateType_Done = 10
} ;
#line 83 "wes.i"
typedef enum PayloadPlaceStateType PayloadPlaceStateType;
#line 85
enum AutoMode {
    Auto_TakeOff = 0,
    Auto_WP = 1,
    Auto_Land = 2,
    Auto_RTL = 3,
    Auto_CircleMoveToEdge = 4,
    Auto_Circle = 5,
    Auto_Spline = 6,
    Auto_NavGuided = 7,
    Auto_Loiter = 8,
    Auto_NavPayloadPlace = 9
} ;
#line 97 "wes.i"
typedef enum AutoMode AutoMode;
#line 100
enum GuidedMode {
    Guided_TakeOff = 0,
    Guided_WP = 1,
    Guided_Velocity = 2,
    Guided_PosVel = 3,
    Guided_Angle = 4
} ;
#line 107 "wes.i"
typedef enum GuidedMode GuidedMode;
#line 110
enum RTLState {
    RTL_InitialClimb = 0,
    RTL_ReturnHome = 1,
    RTL_LoiterAtHome = 2,
    RTL_FinalDescent = 3,
    RTL_Land = 4
} ;
#line 117 "wes.i"
typedef enum RTLState RTLState;
#line 120
enum SmartRTLState {
    SmartRTL_WaitForPathCleanup = 0,
    SmartRTL_PathFollow = 1,
    SmartRTL_PreLandPosition = 2,
    SmartRTL_Descend = 3,
    SmartRTL_Land = 4
} ;
#line 129
enum AltHoldModeState {
    AltHold_MotorStopped = 0,
    AltHold_Takeoff = 1,
    AltHold_Flying = 2,
    AltHold_Landed = 3
} ;
#line 137
enum LoiterModeState {
    Loiter_MotorStopped = 0,
    Loiter_Takeoff = 1,
    Loiter_Flying = 2,
    Loiter_Landed = 3
} ;
#line 145
enum SportModeState {
    Sport_MotorStopped = 0,
    Sport_Takeoff = 1,
    Sport_Flying = 2,
    Sport_Landed = 3
} ;
#line 153
enum FlipState {
    Flip_Start = 0,
    Flip_Roll = 1,
    Flip_Pitch_A = 2,
    Flip_Pitch_B = 3,
    Flip_Recover = 4,
    Flip_Abandon = 5
} ;
#line 163
enum ThrowModeStage {
    Throw_Disarmed = 0,
    Throw_Detecting = 1,
    Throw_Uprighting = 2,
    Throw_HgtStabilise = 3,
    Throw_PosHold = 4
} ;
#line 171 "wes.i"
typedef enum ThrowModeStage ThrowModeStage;
#line 174
enum ThrowModeType {
    ThrowType_Upward = 0,
    ThrowType_Drop = 1
} ;
#line 179 "wes.i"
struct __anonstruct_rangefinder_state_1 {
   int enabled : 1 ;
   int alt_healthy : 1 ;
   int16_t alt_cm ;
   uint32_t last_healthy_ms ;
   int8_t glitch_count ;
};
#line 179 "wes.i"
struct __anonstruct____missing_field_name_3 {
   uint8_t unused1 : 1 ;
   uint8_t simple_mode : 2 ;
   uint8_t pre_arm_rc_check : 1 ;
   uint8_t pre_arm_check : 1 ;
   uint8_t auto_armed : 1 ;
   uint8_t logging_started : 1 ;
   uint8_t land_complete : 1 ;
   uint8_t new_radio_frame : 1 ;
   uint8_t usb_connected : 1 ;
   uint8_t rc_receiver_present : 1 ;
   uint8_t compass_mot : 1 ;
   uint8_t motor_test : 1 ;
   uint8_t initialised : 1 ;
   uint8_t land_complete_maybe : 1 ;
   uint8_t throttle_zero : 1 ;
   uint8_t system_time_set : 1 ;
   uint8_t gps_base_pos_set : 1 ;
   uint8_t using_interlock : 1 ;
   uint8_t motor_emergency_stop : 1 ;
   uint8_t land_repo_active : 1 ;
   uint8_t motor_interlock_switch : 1 ;
   uint8_t in_arming_delay : 1 ;
};
#line 179 "wes.i"
union __anonunion_ap_2 {
   struct __anonstruct____missing_field_name_3 __annonCompField1 ;
   uint32_t value ;
};
#line 179 "wes.i"
struct __anonstruct_control_switch_state_4 {
   int8_t debounced_switch_position ;
   int8_t last_switch_position ;
   uint32_t last_edge_time_ms ;
};
#line 179 "wes.i"
struct __anonstruct_takeoff_state_5 {
   bool running ;
   float max_speed ;
   float alt_delta ;
   uint32_t start_ms ;
};
#line 179 "wes.i"
struct __anonstruct_failsafe_6 {
   uint8_t rc_override_active : 1 ;
   uint8_t radio : 1 ;
   uint8_t battery : 1 ;
   uint8_t gcs : 1 ;
   uint8_t ekf : 1 ;
   uint8_t terrain : 1 ;
   uint8_t adsb : 1 ;
   int8_t radio_counter ;
   uint32_t last_heartbeat_ms ;
   uint32_t terrain_first_failure_ms ;
   uint32_t terrain_last_failure_ms ;
};
#line 179 "wes.i"
struct __anonstruct_sensor_health_7 {
   uint8_t baro : 1 ;
   uint8_t compass : 1 ;
   uint8_t primary_gps ;
};
#line 179 "wes.i"
struct __anonstruct_nav_payload_place_8 {
   PayloadPlaceStateType state ;
   uint32_t hover_start_timestamp ;
   float hover_throttle_level ;
   uint32_t descend_start_timestamp ;
   uint32_t place_start_timestamp ;
   float descend_throttle_level ;
   float descend_start_altitude ;
   float descend_max ;
};
#line 179 "wes.i"
struct __anonstruct_rtl_path_9 {
   bool land ;
   bool terrain_used ;
};
#line 179 "wes.i"
struct __anonstruct_throw_state_10 {
   ThrowModeStage stage ;
   ThrowModeStage prev_stage ;
   uint32_t last_log_ms ;
   bool nextmode_attempted ;
   uint32_t free_fall_start_ms ;
   float free_fall_start_velz ;
};
#line 179 "wes.i"
struct __anonstruct_gndeffect_state_11 {
   bool takeoff_expected ;
   bool touchdown_expected ;
   uint32_t takeoff_time_ms ;
   float takeoff_alt_cm ;
};
#line 179 "wes.i"
struct Copter {
   uint8_t command_ack_counter ;
   int in_log_download ;
   struct __anonstruct_rangefinder_state_1 rangefinder_state ;
   float ekfGndSpdLimit ;
   float ekfNavVelGainScaler ;
   uint32_t ekfYawReset_ms ;
   int8_t ekf_primary_core ;
   union __anonunion_ap_2 ap ;
   control_mode_t control_mode ;
   mode_reason_t control_mode_reason ;
   control_mode_t prev_control_mode ;
   mode_reason_t prev_control_mode_reason ;
   struct __anonstruct_control_switch_state_4 control_switch_state ;
   struct __anonstruct_takeoff_state_5 takeoff_state ;
   float auto_takeoff_no_nav_alt_cm ;
   uint8_t receiver_rssi ;
   struct __anonstruct_failsafe_6 failsafe ;
   struct __anonstruct_sensor_health_7 sensor_health ;
   float scaleLongDown ;
   int32_t wp_bearing ;
   int32_t home_bearing ;
   int32_t home_distance ;
   uint32_t wp_distance ;
   LandStateType land_state ;
   struct __anonstruct_nav_payload_place_8 nav_payload_place ;
   AutoMode auto_mode ;
   GuidedMode guided_mode ;
   RTLState rtl_state ;
   bool rtl_state_complete ;
   struct __anonstruct_rtl_path_9 rtl_path ;
   bool circle_pilot_yaw_override ;
   float simple_cos_yaw ;
   float simple_sin_yaw ;
   int32_t super_simple_last_bearing ;
   float super_simple_cos_yaw ;
   float super_simple_sin_yaw ;
   int32_t initial_armed_bearing ;
   uint16_t loiter_time_max ;
   uint32_t loiter_time ;
   uint32_t brake_timeout_start ;
   uint32_t brake_timeout_ms ;
   int32_t nav_delay_time_max ;
   uint32_t nav_delay_time_start ;
   struct __anonstruct_throw_state_10 throw_state ;
   uint32_t control_sensors_present ;
   uint32_t control_sensors_enabled ;
   uint32_t control_sensors_health ;
   int16_t climb_rate ;
   float target_rangefinder_alt ;
   int32_t baro_alt ;
   float baro_climbrate ;
   uint8_t auto_yaw_mode ;
   float yaw_look_at_WP_bearing ;
   int32_t yaw_look_at_heading ;
   int16_t yaw_look_at_heading_slew ;
   float yaw_look_ahead_bearing ;
   int32_t condition_value ;
   uint32_t condition_start ;
   float G_Dt ;
   int16_t pmTest1 ;
   uint32_t fast_loopTimer ;
   uint16_t mainLoop_count ;
   uint32_t rtl_loiter_start_time ;
   uint32_t arm_time_ms ;
   uint8_t auto_trim_counter ;
   bool in_mavlink_delay ;
   bool gcs_out_of_time ;
   uint32_t last_radio_update_ms ;
   struct __anonstruct_gndeffect_state_11 gndeffect_state ;
   bool upgrading_frame_params ;
};
/* compiler builtin: 
   void __builtin_va_copy(__builtin_va_list  , __builtin_va_list  ) ;  */
/* compiler builtin: 
   double __builtin_huge_val(void) ;  */
/* compiler builtin: 
   int __builtin_clzl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_frexpf(float  , int * ) ;  */
/* compiler builtin: 
   long double __builtin_fmodl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_atan(double  ) ;  */
/* compiler builtin: 
   int __builtin___fprintf_chk(void * , int  , char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_ceilf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_and_and_fetch(...) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_or(...) ;  */
/* compiler builtin: 
   void __builtin_return(void const   * ) ;  */
/* compiler builtin: 
   int __builtin_popcountll(unsigned long long  ) ;  */
/* compiler builtin: 
   long double __builtin_asinl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_atanf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ffsll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_addps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strcspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   float __builtin_asinf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_maxps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpckhps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_acos(double  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack(void) ;  */
/* compiler builtin: 
   char *__builtin___strncpy_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___sprintf_chk(char * , int  , unsigned long  , char const   *  , ...) ;  */
/* compiler builtin: 
   double __builtin_powi(double  , int  ) ;  */
/* compiler builtin: 
   char *__builtin_strchr(char * , int  ) ;  */
/* compiler builtin: 
   char *__builtin___strncat_chk(char * , char const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_huge_vall(void) ;  */
/* compiler builtin: 
   int __builtin_ffsl(unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin___vprintf_chk(int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_unpcklps(float __attribute__((____vector_size____(16)))   ,
                                                                           float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   char *__builtin_strncat(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctzll(unsigned long long  ) ;  */
/* compiler builtin: 
   double __builtin_cosh(double  ) ;  */
/* compiler builtin: 
   void __builtin_stdarg_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_tanhf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_xor(...) ;  */
/* compiler builtin: 
   void *__builtin_mempcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_frexpl(long double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_tanf(float  ) ;  */
/* compiler builtin: 
   long double __builtin_logl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_sqrtl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_parity(unsigned int  ) ;  */
/* compiler builtin: 
   void __builtin_va_arg(__builtin_va_list  , unsigned long  , void * ) ;  */
/* compiler builtin: 
   long __builtin_expect(long  , long  ) ;  */
/* compiler builtin: 
   long double __builtin_coshl(long double  ) ;  */
/* compiler builtin: 
   long double __builtin_cosl(long double  ) ;  */
/* compiler builtin: 
   float __builtin_cosf(float  ) ;  */
/* compiler builtin: 
   int __builtin___printf_chk(int  , char const   *  , ...) ;  */
/* compiler builtin: 
   void __sync_synchronize(...) ;  */
/* compiler builtin: 
   long double __builtin_acosl(long double  ) ;  */
/* compiler builtin: 
   int __builtin___vfprintf_chk(void * , int  , char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   void *__builtin___mempcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_or_and_fetch(...) ;  */
/* compiler builtin: 
   void __builtin_prefetch(void const   *  , ...) ;  */
/* compiler builtin: 
   long double __builtin_nansl(char const   * ) ;  */
/* compiler builtin: 
   double __builtin_fmod(double  ) ;  */
/* compiler builtin: 
   int __builtin_clz(unsigned int  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_val_compare_and_swap(...) ;  */
/* compiler builtin: 
   double __builtin_log10(double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcat_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_tanh(double  ) ;  */
/* compiler builtin: 
   float __builtin_modff(float  , float * ) ;  */
/* compiler builtin: 
   double __builtin_sin(double  ) ;  */
/* compiler builtin: 
   double __builtin_frexp(double  , int * ) ;  */
/* compiler builtin: 
   float __builtin_acosf(float  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_add_and_fetch(...) ;  */
/* compiler builtin: 
   long double __builtin_sinhl(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___stpcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_ldexpl(long double  , int  ) ;  */
/* compiler builtin: 
   double __builtin_fabs(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_nand(...) ;  */
/* compiler builtin: 
   void *__builtin_apply(void (*)() , void * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_sinf(float  ) ;  */
/* compiler builtin: 
   double __builtin_ceil(double  ) ;  */
/* compiler builtin: 
   long double __builtin_powil(long double  , int  ) ;  */
/* compiler builtin: 
   void __builtin_va_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   long double __builtin_expl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_constant_p(int  ) ;  */
/* compiler builtin: 
   double __builtin_log(double  ) ;  */
/* compiler builtin: 
   float __builtin_expf(float  ) ;  */
/* compiler builtin: 
   int __builtin_types_compatible_p(unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_ctz(unsigned int  ) ;  */
/* compiler builtin: 
   long double __builtin_atan2l(long double  , long double  ) ;  */
/* compiler builtin: 
   void *__builtin_apply_args(void) ;  */
/* compiler builtin: 
   char *__builtin_strpbrk(char const   * , char const   * ) ;  */
/* compiler builtin: 
   char *__builtin_strcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   double __builtin_sqrt(double  ) ;  */
/* compiler builtin: 
   __builtin_va_list __builtin_next_arg(void) ;  */
/* compiler builtin: 
   float __builtin_logf(float  ) ;  */
/* compiler builtin: 
   float __builtin_log10f(float  ) ;  */
/* compiler builtin: 
   long double __builtin_fabsl(long double  ) ;  */
/* compiler builtin: 
   unsigned long __builtin_strlen(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_floorl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_ffs(unsigned int  ) ;  */
/* compiler builtin: 
   double __builtin_inf(void) ;  */
/* compiler builtin: 
   float __builtin_floorf(float  ) ;  */
/* compiler builtin: 
   void *__builtin_memcpy(void * , void const   * , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin___memcpy_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_sub_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin_parityl(unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_nand_and_fetch(...) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_subps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_lock_test_and_set(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_strspn(char const   * , char const   * ) ;  */
/* compiler builtin: 
   void __builtin_varargs_start(__builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin_parityll(unsigned long long  ) ;  */
/* compiler builtin: 
   void __builtin_va_end(__builtin_va_list  ) ;  */
/* compiler builtin: 
   void __builtin_bzero(void * , unsigned long  ) ;  */
/* compiler builtin: 
   int __builtin_strncmp(char const   * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   double __builtin_nan(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_xor_and_fetch(...) ;  */
/* compiler builtin: 
   int __builtin___vsprintf_chk(char * , int  , unsigned long  , char const   * ,
                                __builtin_va_list  ) ;  */
/* compiler builtin: 
   int __builtin___snprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                char const   *  , ...) ;  */
/* compiler builtin: 
   float __builtin_sqrtf(float  ) ;  */
/* compiler builtin: 
   double __builtin_nans(char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_atanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_exp(double  ) ;  */
/* compiler builtin: 
   int __builtin_clzll(unsigned long long  ) ;  */
/* compiler builtin: 
   float __builtin_huge_valf(void) ;  */
/* compiler builtin: 
   float __builtin_coshf(float  ) ;  */
/* compiler builtin: 
   float __builtin_nansf(char const   * ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_add(...) ;  */
/* compiler builtin: 
   int __builtin___vsnprintf_chk(char * , unsigned long  , int  , unsigned long  ,
                                 char const   * , __builtin_va_list  ) ;  */
/* compiler builtin: 
   float __builtin_nanf(char const   * ) ;  */
/* compiler builtin: 
   int __builtin_strcmp(char const   * , char const   * ) ;  */
/* compiler builtin: 
   _Bool __sync_bool_compare_and_swap(...) ;  */
/* compiler builtin: 
   float __builtin_ldexpf(float  , int  ) ;  */
/* compiler builtin: 
   double __builtin_atan2(double  , double  ) ;  */
/* compiler builtin: 
   int __builtin_popcountl(unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_powif(float  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_ceill(long double  ) ;  */
/* compiler builtin: 
   char *__builtin___strcpy_chk(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_log10l(long double  ) ;  */
/* compiler builtin: 
   void *__builtin___memmove_chk(void * , void const   * , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_and(...) ;  */
/* compiler builtin: 
   void *__builtin_return_address(unsigned int  ) ;  */
/* compiler builtin: 
   float __builtin_fabsf(float  ) ;  */
/* compiler builtin: 
   double __builtin_floor(double  ) ;  */
/* compiler builtin: 
   double __builtin_cos(double  ) ;  */
/* compiler builtin: 
   void __attribute__((__overloaded__))  __sync_fetch_and_sub(...) ;  */
/* compiler builtin: 
   unsigned long __builtin_object_size(void * , int  ) ;  */
/* compiler builtin: 
   void *__builtin_memset(void * , int  , int  ) ;  */
/* compiler builtin: 
   void *__builtin_alloca(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_nanl(char const   * ) ;  */
/* compiler builtin: 
   float __builtin_atan2f(float  , float  ) ;  */
/* compiler builtin: 
   int __builtin_popcount(unsigned int  ) ;  */
/* compiler builtin: 
   int __builtin_va_arg_pack_len(void) ;  */
/* compiler builtin: 
   long double __builtin_tanl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_sinh(double  ) ;  */
/* compiler builtin: 
   void __builtin_bcopy(void const   * , void * , unsigned long  ) ;  */
/* compiler builtin: 
   void __sync_lock_release(...) ;  */
/* compiler builtin: 
   long double __builtin_modfl(long double  , long double * ) ;  */
/* compiler builtin: 
   char *__builtin_stpcpy(char * , char const   * ) ;  */
/* compiler builtin: 
   long double __builtin_sinl(long double  ) ;  */
/* compiler builtin: 
   double __builtin_asin(double  ) ;  */
/* compiler builtin: 
   float __builtin_sinhf(float  ) ;  */
/* compiler builtin: 
   int __builtin_ctzl(unsigned long  ) ;  */
/* compiler builtin: 
   long double __builtin_tanhl(long double  ) ;  */
/* compiler builtin: 
   int __builtin_bswap32(int  ) ;  */
/* compiler builtin: 
   double __builtin_ldexp(double  , int  ) ;  */
/* compiler builtin: 
   long double __builtin_infl(void) ;  */
/* compiler builtin: 
   long __builtin_bswap64(long  ) ;  */
/* compiler builtin: 
   float __builtin_fmodf(float  ) ;  */
/* compiler builtin: 
   float __attribute__((____vector_size____(16)))  __builtin_ia32_mulps(float __attribute__((____vector_size____(16)))   ,
                                                                        float __attribute__((____vector_size____(16)))   ) ;  */
/* compiler builtin: 
   double __builtin_tan(double  ) ;  */
/* compiler builtin: 
   char *__builtin_strncpy(char * , char const   * , unsigned long  ) ;  */
/* compiler builtin: 
   float __builtin_inff(void) ;  */
/* compiler builtin: 
   void *__builtin___memset_chk(void * , int  , unsigned long  , unsigned long  ) ;  */
/* compiler builtin: 
   void *__builtin_frame_address(unsigned int  ) ;  */
void __deserialize_LandStateType(enum LandStateType *ptr , int fd ) ;
void __deserialize___anonstruct_rtl_path_9(struct __anonstruct_rtl_path_9 *ptr , int fd ) ;
void __serialize_ThrowModeStage(enum ThrowModeStage *ptr , int fd ) ;
void __deserialize_scalarInt16(short *ptr , int fd ) ;
void __serialize___anonstruct_throw_state_10(struct __anonstruct_throw_state_10 *ptr ,
                                             int fd ) ;
void __serialize___anonstruct_gndeffect_state_11(struct __anonstruct_gndeffect_state_11 *ptr ,
                                                 int fd ) ;
void __serialize_control_mode_t(enum control_mode_t *ptr , int fd ) ;
void __deserialize_scalarFloat32(float *ptr , int fd ) ;
void __deserialize___anonstruct_sensor_health_7(struct __anonstruct_sensor_health_7 *ptr ,
                                                int fd ) ;
void __serialize___anonunion_ap_2(union __anonunion_ap_2 *ptr , int fd ) ;
void __deserialize___anonstruct_throw_state_10(struct __anonstruct_throw_state_10 *ptr ,
                                               int fd ) ;
void __serialize___anonstruct____missing_field_name_3(struct __anonstruct____missing_field_name_3 *ptr ,
                                                      int fd ) ;
void __deserialize_RTLState(enum RTLState *ptr , int fd ) ;
void __serialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __deserialize_ThrowModeStage(enum ThrowModeStage *ptr , int fd ) ;
void __deserialize___anonstruct_gndeffect_state_11(struct __anonstruct_gndeffect_state_11 *ptr ,
                                                   int fd ) ;
void __serialize_Copter(struct Copter *ptr , int fd ) ;
void __deserialize___anonstruct_failsafe_6(struct __anonstruct_failsafe_6 *ptr , int fd ) ;
void __deserialize_GuidedMode(enum GuidedMode *ptr , int fd ) ;
void __serialize_LandStateType(enum LandStateType *ptr , int fd ) ;
void __serialize___anonstruct_takeoff_state_5(struct __anonstruct_takeoff_state_5 *ptr ,
                                              int fd ) ;
void __serialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) ;
void __serialize___anonstruct_failsafe_6(struct __anonstruct_failsafe_6 *ptr , int fd ) ;
void __deserialize_control_mode_t(enum control_mode_t *ptr , int fd ) ;
void __deserialize_Copter(struct Copter *ptr , int fd ) ;
void __deserialize_scalarInt32(int *ptr , int fd ) ;
void __serialize_scalarFloat32(float *ptr , int fd ) ;
void __deserialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) ;
void __deserialize_AutoMode(enum AutoMode *ptr , int fd ) ;
void __serialize___anonstruct_sensor_health_7(struct __anonstruct_sensor_health_7 *ptr ,
                                              int fd ) ;
void __serialize_scalarInt32(int *ptr , int fd ) ;
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) ;
void __serialize___anonstruct_rtl_path_9(struct __anonstruct_rtl_path_9 *ptr , int fd ) ;
void __serialize_PayloadPlaceStateType(enum PayloadPlaceStateType *ptr , int fd ) ;
void __deserialize___anonstruct____missing_field_name_3(struct __anonstruct____missing_field_name_3 *ptr ,
                                                        int fd ) ;
void __serialize___anonstruct_rangefinder_state_1(struct __anonstruct_rangefinder_state_1 *ptr ,
                                                  int fd ) ;
void __serialize___anonstruct_control_switch_state_4(struct __anonstruct_control_switch_state_4 *ptr ,
                                                     int fd ) ;
void __serialize_scalarInt16(short *ptr , int fd ) ;
void __serialize___anonstruct_nav_payload_place_8(struct __anonstruct_nav_payload_place_8 *ptr ,
                                                  int fd ) ;
void __deserialize___anonstruct_control_switch_state_4(struct __anonstruct_control_switch_state_4 *ptr ,
                                                       int fd ) ;
void __deserialize_PayloadPlaceStateType(enum PayloadPlaceStateType *ptr , int fd ) ;
void __deserialize___anonstruct_nav_payload_place_8(struct __anonstruct_nav_payload_place_8 *ptr ,
                                                    int fd ) ;
void __serialize_GuidedMode(enum GuidedMode *ptr , int fd ) ;
void __serialize_AutoMode(enum AutoMode *ptr , int fd ) ;
void __deserialize___anonunion_ap_2(union __anonunion_ap_2 *ptr , int fd ) ;
void __deserialize___anonstruct_takeoff_state_5(struct __anonstruct_takeoff_state_5 *ptr ,
                                                int fd ) ;
void __serialize_RTLState(enum RTLState *ptr , int fd ) ;
void __deserialize___anonstruct_rangefinder_state_1(struct __anonstruct_rangefinder_state_1 *ptr ,
                                                    int fd ) ;
void __deserialize_LandStateType(enum LandStateType *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize___anonstruct_rtl_path_9(struct __anonstruct_rtl_path_9 *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->land, fd);
  __deserialize_scalarInt8(& ptr->terrain_used, fd);
}
}
void __serialize_ThrowModeStage(enum ThrowModeStage *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_scalarInt16(short *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 2);
}
}
void __serialize___anonstruct_throw_state_10(struct __anonstruct_throw_state_10 *ptr ,
                                             int fd ) 
{ 


  {
  __serialize_ThrowModeStage(& ptr->stage, fd);
  __serialize_ThrowModeStage(& ptr->prev_stage, fd);
  __serialize_scalarInt32(& ptr->last_log_ms, fd);
  __serialize_scalarInt8(& ptr->nextmode_attempted, fd);
  __serialize_scalarInt32(& ptr->free_fall_start_ms, fd);
  __serialize_scalarFloat32(& ptr->free_fall_start_velz, fd);
}
}
void __serialize___anonstruct_gndeffect_state_11(struct __anonstruct_gndeffect_state_11 *ptr ,
                                                 int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->takeoff_expected, fd);
  __serialize_scalarInt8(& ptr->touchdown_expected, fd);
  __serialize_scalarInt32(& ptr->takeoff_time_ms, fd);
  __serialize_scalarFloat32(& ptr->takeoff_alt_cm, fd);
}
}
void __serialize_control_mode_t(enum control_mode_t *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize___anonstruct_sensor_health_7(struct __anonstruct_sensor_health_7 *ptr ,
                                                int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->baro, fd);
  __deserialize_scalarInt8(& ptr->compass, fd);
  __deserialize_scalarInt8(& ptr->primary_gps, fd);
}
}
void __serialize___anonunion_ap_2(union __anonunion_ap_2 *ptr , int fd ) 
{ 


  {
  __serialize___anonstruct____missing_field_name_3(& ptr->__annonCompField1, fd);
  __serialize_scalarInt32(& ptr->value, fd);
}
}
void __deserialize___anonstruct_throw_state_10(struct __anonstruct_throw_state_10 *ptr ,
                                               int fd ) 
{ 


  {
  __deserialize_ThrowModeStage(& ptr->stage, fd);
  __deserialize_ThrowModeStage(& ptr->prev_stage, fd);
  __deserialize_scalarInt32(& ptr->last_log_ms, fd);
  __deserialize_scalarInt8(& ptr->nextmode_attempted, fd);
  __deserialize_scalarInt32(& ptr->free_fall_start_ms, fd);
  __deserialize_scalarFloat32(& ptr->free_fall_start_velz, fd);
}
}
void __serialize___anonstruct____missing_field_name_3(struct __anonstruct____missing_field_name_3 *ptr ,
                                                      int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->unused1, fd);
  __serialize_scalarInt8(& ptr->simple_mode, fd);
  __serialize_scalarInt8(& ptr->pre_arm_rc_check, fd);
  __serialize_scalarInt8(& ptr->pre_arm_check, fd);
  __serialize_scalarInt8(& ptr->auto_armed, fd);
  __serialize_scalarInt8(& ptr->logging_started, fd);
  __serialize_scalarInt8(& ptr->land_complete, fd);
  __serialize_scalarInt8(& ptr->new_radio_frame, fd);
  __serialize_scalarInt8(& ptr->usb_connected, fd);
  __serialize_scalarInt8(& ptr->rc_receiver_present, fd);
  __serialize_scalarInt8(& ptr->compass_mot, fd);
  __serialize_scalarInt8(& ptr->motor_test, fd);
  __serialize_scalarInt8(& ptr->initialised, fd);
  __serialize_scalarInt8(& ptr->land_complete_maybe, fd);
  __serialize_scalarInt8(& ptr->throttle_zero, fd);
  __serialize_scalarInt8(& ptr->system_time_set, fd);
  __serialize_scalarInt8(& ptr->gps_base_pos_set, fd);
  __serialize_scalarInt8(& ptr->using_interlock, fd);
  __serialize_scalarInt8(& ptr->motor_emergency_stop, fd);
  __serialize_scalarInt8(& ptr->land_repo_active, fd);
  __serialize_scalarInt8(& ptr->motor_interlock_switch, fd);
  __serialize_scalarInt8(& ptr->in_arming_delay, fd);
}
}
void __deserialize_RTLState(enum RTLState *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 1);
}
}
void __deserialize_ThrowModeStage(enum ThrowModeStage *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize___anonstruct_gndeffect_state_11(struct __anonstruct_gndeffect_state_11 *ptr ,
                                                   int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->takeoff_expected, fd);
  __deserialize_scalarInt8(& ptr->touchdown_expected, fd);
  __deserialize_scalarInt32(& ptr->takeoff_time_ms, fd);
  __deserialize_scalarFloat32(& ptr->takeoff_alt_cm, fd);
}
}
void __serialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->command_ack_counter, fd);
  __serialize_scalarInt32(& ptr->in_log_download, fd);
  __serialize___anonstruct_rangefinder_state_1(& ptr->rangefinder_state, fd);
  __serialize_scalarFloat32(& ptr->ekfGndSpdLimit, fd);
  __serialize_scalarFloat32(& ptr->ekfNavVelGainScaler, fd);
  __serialize_scalarInt32(& ptr->ekfYawReset_ms, fd);
  __serialize_scalarInt8(& ptr->ekf_primary_core, fd);
  __serialize___anonunion_ap_2(& ptr->ap, fd);
  __serialize_control_mode_t(& ptr->control_mode, fd);
  __serialize_mode_reason_t(& ptr->control_mode_reason, fd);
  __serialize_control_mode_t(& ptr->prev_control_mode, fd);
  __serialize_mode_reason_t(& ptr->prev_control_mode_reason, fd);
  __serialize___anonstruct_control_switch_state_4(& ptr->control_switch_state, fd);
  __serialize___anonstruct_takeoff_state_5(& ptr->takeoff_state, fd);
  __serialize_scalarFloat32(& ptr->auto_takeoff_no_nav_alt_cm, fd);
  __serialize_scalarInt8(& ptr->receiver_rssi, fd);
  __serialize___anonstruct_failsafe_6(& ptr->failsafe, fd);
  __serialize___anonstruct_sensor_health_7(& ptr->sensor_health, fd);
  __serialize_scalarFloat32(& ptr->scaleLongDown, fd);
  __serialize_scalarInt32(& ptr->wp_bearing, fd);
  __serialize_scalarInt32(& ptr->home_bearing, fd);
  __serialize_scalarInt32(& ptr->home_distance, fd);
  __serialize_scalarInt32(& ptr->wp_distance, fd);
  __serialize_LandStateType(& ptr->land_state, fd);
  __serialize___anonstruct_nav_payload_place_8(& ptr->nav_payload_place, fd);
  __serialize_AutoMode(& ptr->auto_mode, fd);
  __serialize_GuidedMode(& ptr->guided_mode, fd);
  __serialize_RTLState(& ptr->rtl_state, fd);
  __serialize_scalarInt8(& ptr->rtl_state_complete, fd);
  __serialize___anonstruct_rtl_path_9(& ptr->rtl_path, fd);
  __serialize_scalarInt8(& ptr->circle_pilot_yaw_override, fd);
  __serialize_scalarFloat32(& ptr->simple_cos_yaw, fd);
  __serialize_scalarFloat32(& ptr->simple_sin_yaw, fd);
  __serialize_scalarInt32(& ptr->super_simple_last_bearing, fd);
  __serialize_scalarFloat32(& ptr->super_simple_cos_yaw, fd);
  __serialize_scalarFloat32(& ptr->super_simple_sin_yaw, fd);
  __serialize_scalarInt32(& ptr->initial_armed_bearing, fd);
  __serialize_scalarInt16(& ptr->loiter_time_max, fd);
  __serialize_scalarInt32(& ptr->loiter_time, fd);
  __serialize_scalarInt32(& ptr->brake_timeout_start, fd);
  __serialize_scalarInt32(& ptr->brake_timeout_ms, fd);
  __serialize_scalarInt32(& ptr->nav_delay_time_max, fd);
  __serialize_scalarInt32(& ptr->nav_delay_time_start, fd);
  __serialize___anonstruct_throw_state_10(& ptr->throw_state, fd);
  __serialize_scalarInt32(& ptr->control_sensors_present, fd);
  __serialize_scalarInt32(& ptr->control_sensors_enabled, fd);
  __serialize_scalarInt32(& ptr->control_sensors_health, fd);
  __serialize_scalarInt16(& ptr->climb_rate, fd);
  __serialize_scalarFloat32(& ptr->target_rangefinder_alt, fd);
  __serialize_scalarInt32(& ptr->baro_alt, fd);
  __serialize_scalarFloat32(& ptr->baro_climbrate, fd);
  __serialize_scalarInt8(& ptr->auto_yaw_mode, fd);
  __serialize_scalarFloat32(& ptr->yaw_look_at_WP_bearing, fd);
  __serialize_scalarInt32(& ptr->yaw_look_at_heading, fd);
  __serialize_scalarInt16(& ptr->yaw_look_at_heading_slew, fd);
  __serialize_scalarFloat32(& ptr->yaw_look_ahead_bearing, fd);
  __serialize_scalarInt32(& ptr->condition_value, fd);
  __serialize_scalarInt32(& ptr->condition_start, fd);
  __serialize_scalarFloat32(& ptr->G_Dt, fd);
  __serialize_scalarInt16(& ptr->pmTest1, fd);
  __serialize_scalarInt32(& ptr->fast_loopTimer, fd);
  __serialize_scalarInt16(& ptr->mainLoop_count, fd);
  __serialize_scalarInt32(& ptr->rtl_loiter_start_time, fd);
  __serialize_scalarInt32(& ptr->arm_time_ms, fd);
  __serialize_scalarInt8(& ptr->auto_trim_counter, fd);
  __serialize_scalarInt8(& ptr->in_mavlink_delay, fd);
  __serialize_scalarInt8(& ptr->gcs_out_of_time, fd);
  __serialize_scalarInt32(& ptr->last_radio_update_ms, fd);
  __serialize___anonstruct_gndeffect_state_11(& ptr->gndeffect_state, fd);
  __serialize_scalarInt8(& ptr->upgrading_frame_params, fd);
}
}
void __deserialize___anonstruct_failsafe_6(struct __anonstruct_failsafe_6 *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->rc_override_active, fd);
  __deserialize_scalarInt8(& ptr->radio, fd);
  __deserialize_scalarInt8(& ptr->battery, fd);
  __deserialize_scalarInt8(& ptr->gcs, fd);
  __deserialize_scalarInt8(& ptr->ekf, fd);
  __deserialize_scalarInt8(& ptr->terrain, fd);
  __deserialize_scalarInt8(& ptr->adsb, fd);
  __deserialize_scalarInt8(& ptr->radio_counter, fd);
  __deserialize_scalarInt32(& ptr->last_heartbeat_ms, fd);
  __deserialize_scalarInt32(& ptr->terrain_first_failure_ms, fd);
  __deserialize_scalarInt32(& ptr->terrain_last_failure_ms, fd);
}
}
void __deserialize_GuidedMode(enum GuidedMode *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_LandStateType(enum LandStateType *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize___anonstruct_takeoff_state_5(struct __anonstruct_takeoff_state_5 *ptr ,
                                              int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->running, fd);
  __serialize_scalarFloat32(& ptr->max_speed, fd);
  __serialize_scalarFloat32(& ptr->alt_delta, fd);
  __serialize_scalarInt32(& ptr->start_ms, fd);
}
}
void __serialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize___anonstruct_failsafe_6(struct __anonstruct_failsafe_6 *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->rc_override_active, fd);
  __serialize_scalarInt8(& ptr->radio, fd);
  __serialize_scalarInt8(& ptr->battery, fd);
  __serialize_scalarInt8(& ptr->gcs, fd);
  __serialize_scalarInt8(& ptr->ekf, fd);
  __serialize_scalarInt8(& ptr->terrain, fd);
  __serialize_scalarInt8(& ptr->adsb, fd);
  __serialize_scalarInt8(& ptr->radio_counter, fd);
  __serialize_scalarInt32(& ptr->last_heartbeat_ms, fd);
  __serialize_scalarInt32(& ptr->terrain_first_failure_ms, fd);
  __serialize_scalarInt32(& ptr->terrain_last_failure_ms, fd);
}
}
void __deserialize_control_mode_t(enum control_mode_t *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize_Copter(struct Copter *ptr , int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->command_ack_counter, fd);
  __deserialize_scalarInt32(& ptr->in_log_download, fd);
  __deserialize___anonstruct_rangefinder_state_1(& ptr->rangefinder_state, fd);
  __deserialize_scalarFloat32(& ptr->ekfGndSpdLimit, fd);
  __deserialize_scalarFloat32(& ptr->ekfNavVelGainScaler, fd);
  __deserialize_scalarInt32(& ptr->ekfYawReset_ms, fd);
  __deserialize_scalarInt8(& ptr->ekf_primary_core, fd);
  __deserialize___anonunion_ap_2(& ptr->ap, fd);
  __deserialize_control_mode_t(& ptr->control_mode, fd);
  __deserialize_mode_reason_t(& ptr->control_mode_reason, fd);
  __deserialize_control_mode_t(& ptr->prev_control_mode, fd);
  __deserialize_mode_reason_t(& ptr->prev_control_mode_reason, fd);
  __deserialize___anonstruct_control_switch_state_4(& ptr->control_switch_state, fd);
  __deserialize___anonstruct_takeoff_state_5(& ptr->takeoff_state, fd);
  __deserialize_scalarFloat32(& ptr->auto_takeoff_no_nav_alt_cm, fd);
  __deserialize_scalarInt8(& ptr->receiver_rssi, fd);
  __deserialize___anonstruct_failsafe_6(& ptr->failsafe, fd);
  __deserialize___anonstruct_sensor_health_7(& ptr->sensor_health, fd);
  __deserialize_scalarFloat32(& ptr->scaleLongDown, fd);
  __deserialize_scalarInt32(& ptr->wp_bearing, fd);
  __deserialize_scalarInt32(& ptr->home_bearing, fd);
  __deserialize_scalarInt32(& ptr->home_distance, fd);
  __deserialize_scalarInt32(& ptr->wp_distance, fd);
  __deserialize_LandStateType(& ptr->land_state, fd);
  __deserialize___anonstruct_nav_payload_place_8(& ptr->nav_payload_place, fd);
  __deserialize_AutoMode(& ptr->auto_mode, fd);
  __deserialize_GuidedMode(& ptr->guided_mode, fd);
  __deserialize_RTLState(& ptr->rtl_state, fd);
  __deserialize_scalarInt8(& ptr->rtl_state_complete, fd);
  __deserialize___anonstruct_rtl_path_9(& ptr->rtl_path, fd);
  __deserialize_scalarInt8(& ptr->circle_pilot_yaw_override, fd);
  __deserialize_scalarFloat32(& ptr->simple_cos_yaw, fd);
  __deserialize_scalarFloat32(& ptr->simple_sin_yaw, fd);
  __deserialize_scalarInt32(& ptr->super_simple_last_bearing, fd);
  __deserialize_scalarFloat32(& ptr->super_simple_cos_yaw, fd);
  __deserialize_scalarFloat32(& ptr->super_simple_sin_yaw, fd);
  __deserialize_scalarInt32(& ptr->initial_armed_bearing, fd);
  __deserialize_scalarInt16(& ptr->loiter_time_max, fd);
  __deserialize_scalarInt32(& ptr->loiter_time, fd);
  __deserialize_scalarInt32(& ptr->brake_timeout_start, fd);
  __deserialize_scalarInt32(& ptr->brake_timeout_ms, fd);
  __deserialize_scalarInt32(& ptr->nav_delay_time_max, fd);
  __deserialize_scalarInt32(& ptr->nav_delay_time_start, fd);
  __deserialize___anonstruct_throw_state_10(& ptr->throw_state, fd);
  __deserialize_scalarInt32(& ptr->control_sensors_present, fd);
  __deserialize_scalarInt32(& ptr->control_sensors_enabled, fd);
  __deserialize_scalarInt32(& ptr->control_sensors_health, fd);
  __deserialize_scalarInt16(& ptr->climb_rate, fd);
  __deserialize_scalarFloat32(& ptr->target_rangefinder_alt, fd);
  __deserialize_scalarInt32(& ptr->baro_alt, fd);
  __deserialize_scalarFloat32(& ptr->baro_climbrate, fd);
  __deserialize_scalarInt8(& ptr->auto_yaw_mode, fd);
  __deserialize_scalarFloat32(& ptr->yaw_look_at_WP_bearing, fd);
  __deserialize_scalarInt32(& ptr->yaw_look_at_heading, fd);
  __deserialize_scalarInt16(& ptr->yaw_look_at_heading_slew, fd);
  __deserialize_scalarFloat32(& ptr->yaw_look_ahead_bearing, fd);
  __deserialize_scalarInt32(& ptr->condition_value, fd);
  __deserialize_scalarInt32(& ptr->condition_start, fd);
  __deserialize_scalarFloat32(& ptr->G_Dt, fd);
  __deserialize_scalarInt16(& ptr->pmTest1, fd);
  __deserialize_scalarInt32(& ptr->fast_loopTimer, fd);
  __deserialize_scalarInt16(& ptr->mainLoop_count, fd);
  __deserialize_scalarInt32(& ptr->rtl_loiter_start_time, fd);
  __deserialize_scalarInt32(& ptr->arm_time_ms, fd);
  __deserialize_scalarInt8(& ptr->auto_trim_counter, fd);
  __deserialize_scalarInt8(& ptr->in_mavlink_delay, fd);
  __deserialize_scalarInt8(& ptr->gcs_out_of_time, fd);
  __deserialize_scalarInt32(& ptr->last_radio_update_ms, fd);
  __deserialize___anonstruct_gndeffect_state_11(& ptr->gndeffect_state, fd);
  __deserialize_scalarInt8(& ptr->upgrading_frame_params, fd);
}
}
void __deserialize_scalarInt32(int *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize_scalarFloat32(float *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_mode_reason_t(enum mode_reason_t *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize_AutoMode(enum AutoMode *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __serialize___anonstruct_sensor_health_7(struct __anonstruct_sensor_health_7 *ptr ,
                                              int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->baro, fd);
  __serialize_scalarInt8(& ptr->compass, fd);
  __serialize_scalarInt8(& ptr->primary_gps, fd);
}
}
void __serialize_scalarInt32(int *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize_scalarInt8(unsigned char *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 1);
}
}
void __serialize___anonstruct_rtl_path_9(struct __anonstruct_rtl_path_9 *ptr , int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->land, fd);
  __serialize_scalarInt8(& ptr->terrain_used, fd);
}
}
void __serialize_PayloadPlaceStateType(enum PayloadPlaceStateType *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize___anonstruct____missing_field_name_3(struct __anonstruct____missing_field_name_3 *ptr ,
                                                        int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->unused1, fd);
  __deserialize_scalarInt8(& ptr->simple_mode, fd);
  __deserialize_scalarInt8(& ptr->pre_arm_rc_check, fd);
  __deserialize_scalarInt8(& ptr->pre_arm_check, fd);
  __deserialize_scalarInt8(& ptr->auto_armed, fd);
  __deserialize_scalarInt8(& ptr->logging_started, fd);
  __deserialize_scalarInt8(& ptr->land_complete, fd);
  __deserialize_scalarInt8(& ptr->new_radio_frame, fd);
  __deserialize_scalarInt8(& ptr->usb_connected, fd);
  __deserialize_scalarInt8(& ptr->rc_receiver_present, fd);
  __deserialize_scalarInt8(& ptr->compass_mot, fd);
  __deserialize_scalarInt8(& ptr->motor_test, fd);
  __deserialize_scalarInt8(& ptr->initialised, fd);
  __deserialize_scalarInt8(& ptr->land_complete_maybe, fd);
  __deserialize_scalarInt8(& ptr->throttle_zero, fd);
  __deserialize_scalarInt8(& ptr->system_time_set, fd);
  __deserialize_scalarInt8(& ptr->gps_base_pos_set, fd);
  __deserialize_scalarInt8(& ptr->using_interlock, fd);
  __deserialize_scalarInt8(& ptr->motor_emergency_stop, fd);
  __deserialize_scalarInt8(& ptr->land_repo_active, fd);
  __deserialize_scalarInt8(& ptr->motor_interlock_switch, fd);
  __deserialize_scalarInt8(& ptr->in_arming_delay, fd);
}
}
void __serialize___anonstruct_rangefinder_state_1(struct __anonstruct_rangefinder_state_1 *ptr ,
                                                  int fd ) 
{ 


  {
  __serialize_scalarInt32(& ptr->enabled, fd);
  __serialize_scalarInt32(& ptr->alt_healthy, fd);
  __serialize_scalarInt16(& ptr->alt_cm, fd);
  __serialize_scalarInt32(& ptr->last_healthy_ms, fd);
  __serialize_scalarInt8(& ptr->glitch_count, fd);
}
}
void __serialize___anonstruct_control_switch_state_4(struct __anonstruct_control_switch_state_4 *ptr ,
                                                     int fd ) 
{ 


  {
  __serialize_scalarInt8(& ptr->debounced_switch_position, fd);
  __serialize_scalarInt8(& ptr->last_switch_position, fd);
  __serialize_scalarInt32(& ptr->last_edge_time_ms, fd);
}
}
void __serialize_scalarInt16(short *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 2);
}
}
void __serialize___anonstruct_nav_payload_place_8(struct __anonstruct_nav_payload_place_8 *ptr ,
                                                  int fd ) 
{ 


  {
  __serialize_PayloadPlaceStateType(& ptr->state, fd);
  __serialize_scalarInt32(& ptr->hover_start_timestamp, fd);
  __serialize_scalarFloat32(& ptr->hover_throttle_level, fd);
  __serialize_scalarInt32(& ptr->descend_start_timestamp, fd);
  __serialize_scalarInt32(& ptr->place_start_timestamp, fd);
  __serialize_scalarFloat32(& ptr->descend_throttle_level, fd);
  __serialize_scalarFloat32(& ptr->descend_start_altitude, fd);
  __serialize_scalarFloat32(& ptr->descend_max, fd);
}
}
void __deserialize___anonstruct_control_switch_state_4(struct __anonstruct_control_switch_state_4 *ptr ,
                                                       int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->debounced_switch_position, fd);
  __deserialize_scalarInt8(& ptr->last_switch_position, fd);
  __deserialize_scalarInt32(& ptr->last_edge_time_ms, fd);
}
}
void __deserialize_PayloadPlaceStateType(enum PayloadPlaceStateType *ptr , int fd ) 
{ 


  {
  read(fd, ptr, 4);
}
}
void __deserialize___anonstruct_nav_payload_place_8(struct __anonstruct_nav_payload_place_8 *ptr ,
                                                    int fd ) 
{ 


  {
  __deserialize_PayloadPlaceStateType(& ptr->state, fd);
  __deserialize_scalarInt32(& ptr->hover_start_timestamp, fd);
  __deserialize_scalarFloat32(& ptr->hover_throttle_level, fd);
  __deserialize_scalarInt32(& ptr->descend_start_timestamp, fd);
  __deserialize_scalarInt32(& ptr->place_start_timestamp, fd);
  __deserialize_scalarFloat32(& ptr->descend_throttle_level, fd);
  __deserialize_scalarFloat32(& ptr->descend_start_altitude, fd);
  __deserialize_scalarFloat32(& ptr->descend_max, fd);
}
}
void __serialize_GuidedMode(enum GuidedMode *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __serialize_AutoMode(enum AutoMode *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize___anonunion_ap_2(union __anonunion_ap_2 *ptr , int fd ) 
{ 


  {
  __deserialize___anonstruct____missing_field_name_3(& ptr->__annonCompField1, fd);
  __deserialize_scalarInt32(& ptr->value, fd);
}
}
void __deserialize___anonstruct_takeoff_state_5(struct __anonstruct_takeoff_state_5 *ptr ,
                                                int fd ) 
{ 


  {
  __deserialize_scalarInt8(& ptr->running, fd);
  __deserialize_scalarFloat32(& ptr->max_speed, fd);
  __deserialize_scalarFloat32(& ptr->alt_delta, fd);
  __deserialize_scalarInt32(& ptr->start_ms, fd);
}
}
void __serialize_RTLState(enum RTLState *ptr , int fd ) 
{ 


  {
  write(fd, ptr, 4);
}
}
void __deserialize___anonstruct_rangefinder_state_1(struct __anonstruct_rangefinder_state_1 *ptr ,
                                                    int fd ) 
{ 


  {
  __deserialize_scalarInt32(& ptr->enabled, fd);
  __deserialize_scalarInt32(& ptr->alt_healthy, fd);
  __deserialize_scalarInt16(& ptr->alt_cm, fd);
  __deserialize_scalarInt32(& ptr->last_healthy_ms, fd);
  __deserialize_scalarInt8(& ptr->glitch_count, fd);
}
}
#line 606 "wes.i"
int main(void) 
{ 
  struct Copter myCopter ;
  int fd2 ;
  int fd3 ;

  {
  {
  SERIALIZE: ;
  {
  fd2 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __serialize_Copter(& myCopter, fd2);
  close(fd2);
  }
  }
  {
  DESERIALIZE: ;
  {
  fd3 = open("serialized.data", 514, 504);
  _memoizeMax = 0;
  __deserialize_Copter(& myCopter, fd3);
  close(fd3);
  }
  }
#line 615
  return (0);
}
}
